{
  "id": 11,
  "title": "Một giá trị hợp lý Cấp 3 không có đầu vào",
  "company": "Lumen Ventures",
  "difficulty": "Khó",
  "primary": "Có thể kiểm chứng và đầy đủ của ước tính cấp 3",
  "primaryKey": "verifiability",
  "cf": "CF.2.30–2.32",
  "distractors": ["Chỉ không sai sót (Free from error)", "Thích hợp (Relevance)", "Có thể so sánh (Comparability)", "Kịp thời (Timeliness)"],
  "keywords": ["verif", "range", "input", "indirect", "uncertainty", "CF.2.22", "kiểm chứng"],
  "scenario": "Lumen Ventures đo lường khoản nắm giữ 22% tại một bên được đầu tư chưa niêm yết theo giá trị hợp lý 87 triệu CU tại ngày 31 tháng 12 năm 20X6. Số tiền đến từ một mô hình chiết khấu dòng tiền độc quyền (proprietary discounted-cash-flow model) do một tư vấn bên ngoài duy trì. Thuyết minh chứa một câu: “Giá trị hợp lý dựa trên một mô hình chiết khấu dòng tiền.” Không có đầu vào không quan sát được, không có kịch bản rời rạc, không có khoảng và không có độ nhạy đối với tăng trưởng doanh thu hay lãi suất chiết khấu được thuyết minh. Hai chuyên gia định giá do ủy ban kiểm toán thuê, sử dụng các giả định khác nhau nhưng hợp lý, đã đi đến lần lượt 41 triệu CU và 120 triệu CU. Ban quản trị đã từ chối công bố khoảng đó với lý do rằng IFRS yêu cầu một ước tính điểm duy nhất phải được ghi nhận và trình bày một khoảng sẽ làm người sử dụng rối. Giám đốc tài chính lập luận rằng hai chuyên gia khác nhau chứng tỏ Không sai sót (Free from error) không thể đạt — “vậy đừng công bố gì thêm”; rằng 87 triệu CU là thông tin Thích hợp (Relevance) nhất vì là số tư vấn dùng cho fundraising tháng 11; rằng một đối thủ cũng công bố một điểm Level 3 không có input nên Có thể so sánh (Comparability); và rằng bổ sung bảng độ nhạy sẽ lùi ngày duyệt từ 28 tháng 2 sang 15 tháng 3 nên Kịp thời (Timeliness) bị hy sinh. Chi tiết nhiễu: Lumen còn một khoản nắm giữ niêm yết 6 triệu CU đo theo giá đóng cửa, thuyết minh đầy đủ Level 1; ban quản trị nói “chính sách FV của chúng tôi minh bạch.” Email tư vấn ngày 9 tháng 12 liệt kê WACC 11–18% và tăng trưởng 4–22% — chính file đã tạo ra khoảng 41–120 triệu CU — nhưng bị đóng “confidential, not for notes.”",
  "model": "Đặc tính quyết định: Verifiability (CF.2.30–2.32) kết hợp Completeness. Có thể verify một khoảng, không bắt buộc một điểm. Không có input thì không indirect-verify được. CF.2.22: ước tính bất định vẫn useful nếu mô tả rõ uncertainty. Khác biệt giữa hai chuyên gia không tự thành error. Relevance của số fundraising, comparability với peer im lặng, timeliness của ngày duyệt là nhiễu. Khoản Level 1 không cứu Level 3 không tài liệu.",
},
{
  "id": 12,
  "title": "Tiền được trình bày ròng với một khoản thấu chi không liên quan",
  "company": "Orion Logistics",
  "difficulty": "Trung bình–Khó",
  "primary": "Trình bày trung thực — bù trừ khoản không cùng bản chất",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12 / CF.2.27",
  "distractors": ["Trọng yếu (Materiality)", "Dễ hiểu như đặc tính nền tảng", "Kịp thời (Timeliness)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["offset", "set-off", "gross", "thấu chi", "faithful", "unlike", "bù trừ", "trung thực"],
  "scenario": "Orion Logistics trình bày một dòng duy nhất “Tiền và các khoản tương đương tiền 2 triệu CU” như khoản mục đầu tiên của tài sản ngắn hạn. Thuyết minh 17, ở trang 64 của báo cáo thường niên, tiết lộ rằng tập đoàn nắm 48 triệu CU tiền gửi không kỳ hạn (demand deposits) tại Ngân hàng A và một khoản thấu chi 46 triệu CU tại Ngân hàng B. Hai hạn mức nằm ở các khu vực pháp lý khác nhau, khoản thấu chi phải trả ngay khi đòi (repayable on demand), và tập đoàn không có quyền bù trừ có thể thi hành về mặt pháp lý (legally enforceable right of set-off) cũng không có ý định thanh toán ròng. Tờ trình của ban quản trị gửi ủy ban kiểm toán lập luận rằng con số ròng 2 triệu CU cho thấy tốt hơn thanh khoản sẵn có cho tập đoàn như một tổng thể và dễ hiểu hơn hai số gộp lớn gần như triệt tiêu nhau. Các kiểm tra covenant và báo cáo lưu chuyển tiền tệ cũng được lập từ số ròng. Giám đốc tài chính gọi Dễ hiểu (Understandability) là đặc tính nền tảng “trong trường hợp này”; rằng 46 triệu CU thấu chi chỉ bằng 1,8% tổng nguồn vốn nên Trọng yếu (Materiality) không bắt buộc tách; rằng trình bày gộp sẽ buộc viết lại bộ covenant với bốn ngân hàng, tốn 3 tháng và 0,4 triệu CU phí — Ràng buộc chi phí (Cost constraint) và Kịp thời (Timeliness) đều chống. Chi tiết nhiễu: Orion có quyền set-off hợp lệ 1 triệu CU giữa hai tài khoản cùng Ngân hàng A, đã bù trừ đúng; ban quản trị suy ra “vậy netting 48 trừ 46 cũng cùng nguyên tắc.” Email thủ quỹ ngày 2 tháng 1: “Nếu trình bày gộp, tỷ lệ thanh khoản tức thì rơi khỏi covenant. Giữ số 2 triệu CU trên mặt.”",
  "model": "Đặc tính quyết định: Faithful representation. Tiền và thấu chi không có quyền bù trừ là hai hiện tượng khác nhau. Netting làm unlike things look alike (CF.2.27). Understandability không được đánh đổi FR (CF.2.37). Trình bày gộp: cash CU48m và overdraft CU46m. Quyền set-off 1 triệu CU cùng Bank A là nhiễu — không lan sang Bank B. Materiality 1,8% và cost/timeliness của đàm phán lại covenant không biến unlike items thành alike.",
},
{
  "id": 13,
  "title": "Một thương hiệu tự tạo được ghi nhận theo giá trị chiến lược",
  "company": "Aura Cosmetics",
  "difficulty": "Rất khó",
  "primary": "Đánh đổi thích hợp và trình bày trung thực",
  "primaryKey": "trade-off",
  "cf": "CF.2.20–2.22",
  "distractors": ["Chỉ thích hợp (Relevance)", "Chỉ đầy đủ (Completeness)", "Có thể so sánh (Comparability)", "Thận trọng (Prudence)"],
  "keywords": ["trade-off", "IAS 38", "uncertainty", "không ghi nhận", "thuyết minh", "2.22", "đánh đổi"],
  "scenario": "Aura Cosmetics đã gây dựng một thương hiệu tiêu dùng trong hơn hai mươi năm quảng cáo và phát triển sản phẩm. Năm 20X6 ban quản trị muốn người sử dụng thấy giá trị thực của doanh nghiệp và đã ghi nhận một tài sản thương hiệu tự tạo (internally generated brand) 400 triệu CU, với một khoản lãi tương ứng trong lợi nhuận năm. 400 triệu CU là điểm giữa của khoảng 150 triệu CU đến 900 triệu CU của một tư vấn marketing. Không có thị trường hoạt động cho thương hiệu và không có giao dịch có trật tự (orderly transaction) gần đây. IAS 38 cấm ghi nhận thương hiệu tự tạo. Giám đốc tài chính đã nói với kiểm toán rằng Khung khái niệm ưu tiên thông tin thích hợp nhất, giá trị thương hiệu là thông tin thích hợp nhất về nguồn lực của chúng ta, và một xử lý dựa trên Framework nên override một chuẩn mực hạn chế. Không khoảng nào cũng không quy trình ước tính nào được mô tả trong thuyết minh. Ủy ban kiểm toán chia hai phe: phe A nói chỉ cần Thích hợp (Relevance) — “user muốn thấy brand”; phe B nói ghi 400 triệu CU thiếu Đầy đủ (Completeness) vì không có khoảng, hãy ghi rồi thuyết minh 150–900. Một thành viên độc lập muốn không ghi gì cả và gọi đó là Prudence. Giám đốc thương mại chỉ vào hai đối thủ đã “thuyết minh giá trị thương hiệu” trong MD&A (không ghi nhận) và đề xuất Aura phải ghi để Có thể so sánh (Comparability) “mạnh hơn họ.” Chi tiết nhiễu: Aura có một nhãn hàng mua lại năm 20X3, giá gốc 18 triệu CU, đang khấu hao đúng IAS 38; ban quản trị muốn “đồng bộ” bằng cách đánh giá lại nhãn đó lên 90 triệu CU cùng ngày, lấy điểm giữa một khoảng 40–140 triệu CU.",
  "model": "Đặc tính quyết định: áp dụng đồng thời Relevance và Faithful representation — CF.2.20–2.22. Brand tự tạo relevant nhưng measurement uncertainty quá cao (CU150–900m) nên không sufficiently faithful. Framework không override IAS 38. Kênh đúng: thuyết minh, không đưa CU400m vào P/L. Relevance không thắng một mình. Completeness của khoảng, prudence “không ghi,” comparability với MD&A của đối thủ là nhiễu từng phần. Nhãn mua 20X3 (acquired) khác internally generated — đừng đồng bộ bằng revaluation tùy tiện.",
},
{
  "id": 14,
  "title": "Lãi vay đã trả được phân loại lại mỗi năm",
  "company": "Riverbond Plc",
  "difficulty": "Trung bình–Khó",
  "primary": "Có thể so sánh khi phân loại dòng tiền",
  "primaryKey": "comparability",
  "cf": "CF.2.26–2.29",
  "distractors": ["Kịp thời (Timeliness)", "Trọng yếu (Materiality)", "Trung lập (Neutrality)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["comparab", "IAS 7", "operating", "consistency", "restat", "so sánh"],
  "scenario": "Riverbond Plc trình bày báo cáo lưu chuyển tiền tệ theo IAS 7. Lãi vay đã trả khoảng 40 triệu CU một năm đã được phân loại là dòng ra hoạt động trong năm 20X4, là dòng ra tài trợ trong năm 20X5, và lại là dòng ra hoạt động trong năm 20X6. Thuyết minh mỗi năm khẳng định rằng cách phân loại phản ánh tốt hơn bản chất tài trợ của đơn vị. Dòng tiền hoạt động báo cáo năm 20X6 là 90 triệu CU sau khi cộng lại 40 triệu CU lãi vay; theo chính sách năm 20X5 thì dòng tiền hoạt động cùng năm đó đã là 50 triệu CU. Các mô hình bên bán (sell-side) lấy dòng tiền hoạt động làm điểm xuất phát định giá. Các số so sánh chưa được trình bày lại cho lần thay đổi mới nhất. Ban quản trị lưu ý rằng IAS 7 cho phép một sự lựa chọn và do đó coi nhất quán là vấn đề sở thích chứ không phải của thông tin hữu ích. Giám đốc tài chính viết rằng việc nhảy phân loại không phải thiên lệch — Trung lập (Neutrality) ổn vì “cả hai lựa chọn đều có trong chuẩn mực”; rằng 40 triệu CU bằng 2% tổng dòng nên Trọng yếu (Materiality) không bắt buộc restatement; rằng chạy lại số 20X5 tốn 3 tuần lập trình — Ràng buộc chi phí (Cost constraint) và Kịp thời (Timeliness). Chi tiết nhiễu: cổ tức đã trả 12 triệu CU được phân loại nhất quán là dòng ra tài trợ cả ba năm; ban quản trị chỉ vào đó như bằng chứng “chúng tôi nhất quán khi chuẩn mực bắt buộc.” Email CFO ngày 7 tháng 1 năm 20X6: “Năm nay để lãi vay trong operating lại, guidance OCF là 85 triệu CU.”",
  "model": "Đặc tính quyết định: Comparability. IAS 7 cho chọn không xóa yêu cầu nhất quán intra-entity. Nhảy qua lại làm like cash flows trông khác. Thuyết minh giúp tái phân loại một phần (CF.2.38) nhưng không phục hồi hết time-series. Chọn một chính sách và restatement comparatives. Neutrality “cả hai đều được phép,” materiality 2%, cost/timeliness của restatement là nhiễu. Cổ tức nhất quán không cứu lãi vay nhảy. Email guidance OCF là động cơ, không phải bản chất tài trợ.",
},
{
  "id": 15,
  "title": "Nghi ngờ hoạt động liên tục bị lược bỏ vì chưa ghi sổ",
  "company": "Cedar Pharma",
  "difficulty": "Khó",
  "primary": "Thích hợp và đầy đủ của mô tả hoạt động liên tục",
  "primaryKey": "relevance",
  "cf": "CF.2.6 / Ch.3",
  "distractors": ["Thận trọng (Prudence)", "Có thể kiểm chứng (Verifiability)", "Có thể so sánh (Comparability)", "Không sai sót (Free from error)"],
  "keywords": ["going concern", "relevant", "thuyết minh", "40%", "im lặng", "predictive", "thích hợp"],
  "scenario": "Sản phẩm chính của Cedar Pharma, đại diện 70% doanh thu, đang chịu một cuộc rà soát an toàn của cơ quan quản lý. Hai luật sư độc lập đã tư vấn hội đồng rằng có 40% xác suất giấy phép lưu hành sẽ bị rút trong mười hai tháng kể từ ngày 31 tháng 12 năm 20X6, trong trường hợp đó công ty sẽ đi vào giải thể có trật tự (orderly wind-down). Hàng tồn kho và nhà xưởng chuyên dụng sẽ thu hồi được thực chất ít hơn nhiều so với giá trị ghi sổ theo giả định hoạt động liên tục. Ban quản trị đã lập báo cáo tài chính năm 20X6 trên cơ sở hoạt động liên tục (going-concern basis) với không nhấn mạnh sự kiện, không thuyết minh về cuộc rà soát và không mô tả kết cục thay thế. Tờ trình hội đồng nêu rằng chưa phát sinh nghĩa vụ hiện tại, không tài sản nào bị giảm giá nếu giả định hoạt động liên tục, và do đó không có gì thích hợp để báo cáo. Thuyết minh sẽ làm thị trường hoảng và phá hủy giá trị doanh nghiệp. Chủ tịch lập luận rằng im lặng là Prudence “đừng gieo hoảng loạn”; rằng 40% không thể kiểm chứng (Verifiability) vì là xác suất luật sư; rằng đối thủ cùng rà soát cũng không note nên Có thể so sánh (Comparability); và rằng số 20X6 đã ghi đúng nên Không sai sót (Free from error). Chi tiết nhiễu: Cedar có một sản phẩm phụ chiếm 4% doanh thu vừa được gia hạn giấy phép 5 năm ngày 2 tháng 12; ban quản trị đưa tin này lên trang 2 báo cáo quản trị như “bằng chứng franchise ổn định.” Email hội đồng ngày 18 tháng 12: “40% chưa phải probable. Đừng viết going concern. Market cap sẽ bay.”",
  "model": "Đặc tính quyết định: Relevance (và completeness của depiction về entity). 40% khả năng chấm dứt mô hình kinh doanh capable of making a difference dù chưa ghi impairment. Giả định going concern không được im lặng khi có nghi ngờ đáng kể. “Không panic thị trường” là thao túng neutrality, không phải prudence. Verifiability của xác suất luật sư không xóa relevance. Sản phẩm phụ 4% là nhiễu. Free from error của số đã ghi không thay thế disclosure.",
},
{
  "id": 16,
  "title": "Tiền thuê bên liên quan được mô tả là arm’s length",
  "company": "Summit Foods",
  "difficulty": "Khó",
  "primary": "Trình bày trung thực bản chất bên liên quan",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12 / CF.2.11",
  "distractors": ["Có thể so sánh (Comparability)", "Kịp thời (Timeliness)", "Chỉ dễ hiểu (Understandability)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["related", "arm’s", "nature", "phân phối", "faithful", "10 lần", "bên liên quan"],
  "scenario": "Summit Foods trả 12 triệu CU một năm để thuê kho trung tâm từ một công ty thuộc sở hữu gia đình chủ tịch. Hai thẩm định độc lập do ủy ban kiểm toán thu thập đưa tiền thuê thị trường của một cơ sở tương đương ở mức 1,2 triệu CU. Summit ghi nhận toàn bộ 12 triệu CU như tiền thuê hoạt động. Thuyết minh bên liên quan gồm một câu: “Tập đoàn thuê kho bãi từ một bên liên quan theo các điều khoản ngang giá thị trường (arm’s-length terms).” Thuyết minh không xác định bên liên quan là ai, không nêu số tiền, và không so sánh các điều khoản với thị trường. Công ty gia đình báo cáo 12 triệu CU như thu nhập cho thuê thông thường. Ban quản trị cho rằng câu đó đủ vì IAS 24 là một chuẩn mực thuyết minh và giao dịch đã được ghi nhận. Giám đốc tài chính thêm rằng nêu tên gia đình chủ tịch sẽ làm báo cáo “dài và khó đọc” — Dễ hiểu (Understandability); rằng đối thủ cũng chỉ viết một câu IAS 24 nên Có thể so sánh (Comparability); rằng đi thẩm định thêm hai thành phố sẽ lùi ngày duyệt — Kịp thời (Timeliness) và Ràng buộc chi phí (Cost constraint). Chi tiết nhiễu: Summit còn mua bao bì 0,9 triệu CU từ một nhà cung cấp không liên quan theo giá thị trường, thuyết minh rất chi tiết về hợp đồng cung ứng dài hạn như “minh bạch chuỗi cung”; ban quản trị đặt hai thuyết minh cạnh nhau. Email chủ tịch ngày 5 tháng 12 gửi công ty gia đình: “Giữ 12 triệu. Đó là cổ tức dưới hình thức thuê.”",
  "model": "Đặc tính quyết định: Faithful representation kết hợp completeness và materiality theo nature. Gọi arm’s length khi bằng chứng cho thấy gấp 10 lần là mô tả sai. Phần CU10,8m có bản chất phân phối cho bên liên quan. Nature (related party) làm thông tin material dù có thể nhỏ so với tổng chi phí. Understandability, comparability với peer một câu, cost/timeliness của thẩm định thêm là nhiễu. Hợp đồng bao bì không liên quan không cân bằng mô tả sai.",
},
{
  "id": 17,
  "title": "Một khoản giảm giá bị đảo để vượt ngưỡng thưởng",
  "company": "Polar Outdoor",
  "difficulty": "Khó",
  "primary": "Trung lập và trọng yếu định tính",
  "primaryKey": "neutrality",
  "cf": "CF.2.15 / CF.2.11",
  "distractors": ["Có thể so sánh (Comparability)", "Kịp thời (Timeliness)", "Chỉ đầy đủ (Completeness)", "Dễ hiểu (Understandability)"],
  "keywords": ["bonus", "neutral", "đảo", "material", "NRV", "target", "trung lập", "thưởng"],
  "scenario": "Kế hoạch thưởng ban điều hành của Polar Outdoor chi trả nếu lợi nhuận hoạt động vượt 50 triệu CU. Ngày 20 tháng 12 năm 20X6, một rà soát giá trị thuần có thể thực hiện (net realisable value) cuối năm đối với tồn kho theo mùa, được chống lưng bởi dữ liệu đơn hàng sau đó và các kế hoạch hạ giá, cho thấy một khoản giảm 3,2 triệu CU và lợi nhuận còn lại 48,1 triệu CU. Ngày 28 tháng 12 ban quản trị đánh giá lại nhu cầu mùa thời trang và đảo 2,0 triệu CU của khoản giảm đó, nâng lợi nhuận lên 50,1 triệu CU. Email nội bộ lưu hành cùng ngày viết: “Ta chỉ cần thêm 1,9 triệu CU. Hàng luôn có thể được hạ giá vào tháng 1.” Doanh số cùng lô hàng trong tháng 1 năm 20X7 thực hiện các khoản khớp với đánh giá ban đầu ngày 20 tháng 12. Không có đề cập nào về việc đảo, kế hoạch thưởng hay bằng chứng tháng 1 xuất hiện trong báo cáo tài chính. Trưởng phòng kế toán đề xuất ít nhất một thuyết minh về thay đổi ước tính — Đầy đủ (Completeness) — nhưng giám đốc tài chính từ chối vì “user sẽ rối” (Dễ hiểu). Ủy ban lương muốn giữ số 50,1 để “sánh bonus với peer cùng ngành vừa công bố” — Có thể so sánh (Comparability). Phát hành bị hẹn 28 tháng 2; viết thêm note NRV được cho là sẽ lùi sang tháng 3 — Kịp thời (Timeliness). Chi tiết nhiễu: Polar đảo đúng một khoản giảm giá vải vụn 0,1 triệu CU ngày 15 tháng 12 vì một đơn hàng bất ngờ có bằng chứng hợp đồng; ban quản trị gọi đó là “cùng chính sách NRV” với lần đảo 2,0 triệu CU.",
  "model": "Đặc tính quyết định: Neutrality; materiality theo ngữ cảnh bonus. NRV ban đầu có bằng chứng; đảo ngược không có bằng chứng mới, chỉ có target thưởng. CU2m làm thay đổi kết quả thưởng nên qualitative material. Quy trình ước tính bị áp dụng sai nên cũng không free from error. Completeness của note, understandability, comparability bonus với peer, timeliness là nhiễu. Đảo vải vụn 0,1 triệu CU có bằng chứng — khác bản chất.",
},
{
  "id": 18,
  "title": "Hai tàu giống hệt, hai cách xử lý ngược nhau",
  "company": "BlueKeel Shipping",
  "difficulty": "Khó",
  "primary": "Có thể so sánh cộng bản chất hơn hình thức",
  "primaryKey": "comparability",
  "cf": "CF.2.12 / CF.2.27",
  "distractors": ["Kịp thời (Timeliness)", "Trọng yếu (Materiality)", "Ràng buộc chi phí (Cost constraint)", "Chỉ dễ hiểu (Understandability)"],
  "keywords": ["like things", "substance", "lease", "comparab", "nhãn", "so sánh", "bản chất"],
  "scenario": "BlueKeel Shipping nhận bàn giao hai tàu container giống hệt trong cùng tuần, từ cùng bên cho thuê, trên các hợp đồng có cùng thời hạn, cùng bảo đảm giá trị còn lại (residual-value guarantee) và cùng nhịp thanh toán. Hợp đồng tàu A mang tiêu đề “Lease” (Thuê) và được ghi nhận trên Bảng cân đối kế toán. Hợp đồng tàu B mang tiêu đề “Capacity purchase agreement” (Thỏa thuận mua công suất), không bao giờ dùng chữ lease, và không chuyển quyền sở hữu pháp lý; ban quản trị đã để tàu B ngoài Bảng cân đối kế toán và hạch toán các khoản thanh toán vào chi phí khi đến hạn. Hai thỏa thuận cho BlueKeel quyền chỉ đạo việc sử dụng từng tàu trong cùng thời gian và buộc BlueKeel chịu thực chất cùng rủi ro giá trị còn lại. Ban quản trị nói với kiểm toán rằng cả hai cách xử lý đều được các chứng từ cho phép và rằng người sử dụng có thể tự dựng lại khả năng so sánh từ bốn mươi trang thuyết minh. Giám đốc tài chính thêm rằng đưa tàu B lên bảng sẽ làm đòn bẩy tăng 9 điểm phần trăm, vượt covenant — và 9 điểm “chỉ là trình bày, không trọng yếu với dòng tiền.” Viết lại bốn mươi trang thành một chính sách thống nhất được cho là sẽ lùi phát hành (Timeliness) và tốn 0,5 triệu CU luật sư (Cost constraint). Dễ hiểu (Understandability) được viện để giữ nhãn pháp lý khác nhau “vì hợp đồng khác chữ.” Chi tiết nhiễu: BlueKeel còn thuê một sà lan nhỏ 0,8 triệu CU đúng chuẩn IFRS 16, ghi nhận trên bảng; ban quản trị chỉ vào đó như “chúng tôi ghi nhận lease khi hợp đồng gọi là lease.”",
  "model": "Đặc tính quyết định: Comparability gắn với Faithful representation của cùng một hiện tượng. Hai tàu đồng nhất = like things must look alike. Nhãn pháp lý không đổi substance. Thuyết minh bù một phần (CF.2.38) không thay nhận diện nhất quán. Enhancing không cứu unfaithful depiction của Ship B. Materiality “chỉ trình bày,” timeliness, cost, understandability của nhãn là nhiễu. Sà lan nhỏ ghi đúng vì substance là lease — đúng là đối trọng, không phải tiền lệ cho việc nhìn chữ trên bìa.",
},
{
  "id": 19,
  "title": "Một chính sách luôn lấy số xấu nhất",
  "company": "Stonebridge Construction",
  "difficulty": "Rất khó",
  "primary": "Thận trọng không phải bất đối xứng hay bi quan tối đa",
  "primaryKey": "neutrality",
  "cf": "CF.2.16–2.17",
  "distractors": ["Thích hợp (Relevance)", "Đầy đủ (Completeness)", "Có thể so sánh (Comparability)", "Kịp thời (Timeliness)"],
  "keywords": ["prudence", "không bất đối xứng", "neutral", "virtually certain", "mút biên", "thận trọng"],
  "scenario": "Ủy ban kiểm toán của Stonebridge Construction đã ban hành một “chính sách thận trọng” bằng văn bản năm 20X6. Đối với mọi tài sản bất định, công ty phải ghi nhận số thấp nhất trong khoảng hợp lý có thể xảy ra; đối với mọi nợ bất định phải ghi nhận số cao nhất; tài sản tiềm tàng không bao giờ được ghi nhận, kể cả khi dòng vào được đánh giá là gần như chắc chắn (virtually certain). Áp dụng chính sách, một vụ kiện có kết quả có khả năng xảy ra nhiều nhất là 6 triệu CU và khoảng hợp lý có thể xảy ra từ 4 triệu CU đến 9 triệu CU đã được ghi 9 triệu CU. Một yêu cầu bồi thường theo hợp đồng mà luật sư mô tả là gần như chắc chắn thu được 5 triệu CU thì bị bỏ hoàn toàn. Công văn kèm theo của ủy ban nêu rằng chính sách hiện thực hóa khái niệm prudence của Framework và bảo vệ chủ nợ, và rằng bất đối xứng là một đức tính của thông tin tài chính hữu ích. Giám đốc tài chính biện hộ rằng số 9 triệu CU “thích hợp với chủ nợ” (Relevance), rằng thuyết minh cả khoảng 4–9 sẽ làm Đầy đủ (Completeness) phình, rằng hai nhà thầu cùng ngành cũng “luôn lấy mút xấu” nên Có thể so sánh (Comparability), và rằng tranh cãi từng khoản sẽ lùi ngày duyệt (Timeliness). Chi tiết nhiễu: Stonebridge ghi nhận đúng một khoản phải thu xây dựng 14 triệu CU không bất định, có nghiệm thu; ủy ban nói “thấy chưa, chúng tôi không bi quan với mọi tài sản.” Email chủ tịch ủy ban: “Asymmetry protects lenders. That is what prudence means.”",
  "model": "Đặc tính quyết định: hiểu đúng Prudence trong Neutrality — CF.2.16–2.17. Prudence không hàm ý bất đối xứng. Chọn systematically mút biên = bias. Bỏ qua inflow virtually certain là understatement of assets. Mục tiêu BCTC đa mục đích không phải bảo vệ chủ nợ bằng số lệch. Ghi lawsuit khoảng CU6m; ghi nhận compensation CU5m nếu virtually certain. Relevance “cho chủ nợ,” completeness của khoảng, comparability với peer bi quan, timeliness là nhiễu. Khoản phải thu 14 triệu CU không bất định không chứng minh chính sách là trung lập.",
},
{
  "id": 20,
  "title": "Một gian lận nhỏ về số lượng với một câu chuyện lớn",
  "company": "Meadow Dairy",
  "difficulty": "Khó",
  "primary": "Trọng yếu theo bản chất, không theo quy mô",
  "primaryKey": "materiality",
  "cf": "CF.2.11",
  "distractors": ["Ràng buộc chi phí (Cost constraint)", "Kịp thời (Timeliness)", "Có thể so sánh (Comparability)", "Dễ hiểu (Understandability)"],
  "keywords": ["nature", "material", "fraud", "omitting", "obscur", "regulator", "trọng yếu", "gian lận"],
  "scenario": "Kiểm toán nội bộ tại Meadow Dairy phát hiện một quản lý vùng đã chiếm đoạt 180.000 CU tiền công ty trong hai năm. Số tiền bằng 0,04% doanh thu tập đoàn và 0,7% lợi nhuận và đã được hoàn trả đầy đủ. Thủ đoạn được thực hiện bằng cách giả mạo giấy chứng nhận chất lượng sữa cung cấp theo một hợp đồng dinh dưỡng trường công. Một cơ quan an toàn thực phẩm đã mở hồ sơ; luật sư chưa ước tính được tiền phạt. Ban quản trị đã lược bỏ mọi đề cập đến vụ việc khỏi báo cáo tài chính năm 20X6 và khỏi báo cáo quản trị, lập luận rằng số lượng không trọng yếu về mặt định lượng, đã được sửa, và rằng một khoản phạt là không chắc xảy ra và sẽ nhỏ. Không có dự phòng, không có thuyết minh nợ tiềm tàng và không có mô tả cuộc điều tra của cơ quan quản lý. Giám đốc tài chính viết rằng viết note sẽ làm báo cáo “khó đọc với cổ đông lẻ” (Understandability); rằng hai công ty sữa ngang hàng cũng không thuyết minh các vụ thất thoát dưới 0,1% doanh thu (Comparability); rằng chờ luật sư ra số phạt sẽ lùi phát hành sang tháng 4 (Timeliness); và rằng điều tra nội bộ mở rộng tốn 0,3 triệu CU — Ràng buộc chi phí (Cost constraint) “không tương xứng với 180.000 CU.” Chi tiết nhiễu: Meadow có một khoản hao hụt sữa tự nhiên 220.000 CU do vỡ chuỗi lạnh, đã ghi vào giá vốn; ban quản trị gộp 180.000 CU gian lận vào cùng dòng “hao hụt vận hành” trên thuyết minh tồn kho.",
  "model": "Đặc tính quyết định: Materiality — nature or magnitude or both — CF.2.11. Gian lận, hàng giả cho trường học, điều tra cơ quan quản lý: bản chất có thể ảnh hưởng quyết định dù số nhỏ. Omitting và obscuring nằm trong định nghĩa. Hoàn trả không xóa hiện tượng đã xảy ra. Không áp dụng ngưỡng 5% máy móc. Understandability, comparability với peer im lặng, timeliness, cost constraint là nhiễu. Hao hụt chuỗi lạnh 220.000 CU khác bản chất — gộp vào cùng dòng là obscuring.",
},
]
