#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, pathlib

ISSUES = [
{
  "id": 1,
  "title": "Sale or secured borrowing?",
  "company": "BuildTech Co.",
  "difficulty": "Hard",
  "primary": "Faithful representation — substance over form",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12",
  "distractors": ["Relevance", "Materiality", "Neutrality", "Comparability"],
  "keywords": ["substance", "form", "vay", "repurchase", "không bán", "liability", "faithful", "kiểm soát", "secured"],
  "scenario": "BuildTech Co. is preparing its 20X6 financial statements. On 28 December 20X6 it transferred a production line with a carrying amount of CU8 million to FinanceCo and received CU10 million in cash. The contract is headed “Deed of Sale” and states that legal title passes immediately. BuildTech nevertheless continues to operate the machinery in its own factory, remains responsible for maintenance and insurance, and has a contractual obligation to repurchase the same assets on 28 December 20X8 for CU11.45 million. FinanceCo has no right to use, relocate or sell the machinery to a third party during the two-year interval. The CU1.45 million difference equals a market rate of interest on a two-year secured loan. Management has recorded disposal proceeds of CU10 million, a gain of CU2 million and no financial liability, on the grounds that the legal form of the arrangement is a sale completed before year-end.",
  "model": "Đặc tính quyết định: Faithful representation (substance over form) — CF.2.12. Pháp lý gọi là sale nhưng quyền và nghĩa vụ cho thấy đây là khoản vay có tài sản đảm bảo: BuildTech vẫn kiểm soát máy, chịu rủi ro, nghĩa vụ mua lại với lãi suất thị trường. Ghi nhận bán + lãi CU2m + không ghi nợ là mô tả sai hiện tượng kinh tế. Xử lý đúng: giữ máy trên Bảng cân đối, ghi khoản vay CU10m, phân bổ lãi CU1.45m. Relevance vẫn còn nhưng không phải QC quyết định.",
},
{
  "id": 2,
  "title": "Optimistic receivables, pessimistic provisions",
  "company": "SpeedTrade Co.",
  "difficulty": "Hard",
  "primary": "Neutrality — prudence applied inconsistently",
  "primaryKey": "neutrality",
  "cf": "CF.2.15–2.17",
  "distractors": ["Free from error", "Materiality", "Completeness", "Prudence as pessimism"],
  "keywords": ["neutral", "prudence", "bias", "thiên lệch", "không bi quan", "inconsistent", "overstate"],
  "scenario": "SpeedTrade Co. is finalising its 20X6 financial statements. It holds a trade receivable of CU20 million due from a customer that entered formal restructuring in November 20X6. In the same period a competitor issued a legal claim against SpeedTrade; counsel estimates that if SpeedTrade loses it will pay between CU2 million and CU3 million, with a most likely outcome of CU2.4 million. Management has recognised an expected-credit-loss allowance of only 2 per cent of the receivable because the board is “optimistic about customer recovery.” At the same time it has booked a CU10 million provision for the lawsuit because it wishes “to be conservative and to protect next year’s result.” Independent credit analysis commissioned by the audit committee indicates expected losses on the receivable of between CU4 million and CU6 million. No range or alternative estimate is disclosed for either item.",
  "model": "Đặc tính quyết định: Neutrality, được hỗ trợ bởi prudence — CF.2.15–2.17. Prudence không phải chọn số bi quan nhất và không cho phép bất đối xứng có hệ thống. Ở đây lạc quan với phải thu và bi quan với kiện tụng — thiên lệch có chủ đích. Ước tính trung lập nên nằm trong khoảng bằng chứng: ECL khoảng CU5m; provision khoảng CU2.5m, kèm thuyết minh. Không phải free from error thuần túy.",
},
{
  "id": 3,
  "title": "The loss of a major customer",
  "company": "Delta Delivery Co.",
  "difficulty": "Hard",
  "primary": "Relevance — recognition is not required",
  "primaryKey": "relevance",
  "cf": "CF.2.6–2.11",
  "distractors": ["Faithful representation", "Timeliness only", "Free from error", "Comparability"],
  "keywords": ["relevant", "predictive", "thuyết minh", "disclosure", "không ghi nhận", "28", "concentration"],
  "scenario": "Delta Delivery Co. earned revenue of CU100 million and profit of CU8 million in the year ended 31 December 20X6. On 20 December 20X6 its largest customer, which generated 28 per cent of annual revenue and a similar share of operating cash inflows, gave written notice that the delivery contract would not be renewed after 31 January 20X7. Replacement work of comparable scale cannot be mobilised before the third quarter of 20X7. The 20X6 invoices themselves have been recorded correctly and the contract remained legally in force at the reporting date. Management has included no note, no risk disclosure and no discussion of customer concentration, arguing that the contract was still active at year-end and the loss of revenue will occur next year, so the information does not belong in the 20X6 financial statements.",
  "model": "Đặc tính quyết định: Relevance — CF.2.6–2.11. Recognition không phải điều kiện của relevance. Thông báo 20/12 đã xảy ra trước ngày khóa sổ. Predictive value mạnh với dòng tiền 20X7. Không điều chỉnh số 20X6 đã ghi đúng, nhưng PHẢI thuyết minh (tập trung khách hàng, rủi ro). Im lặng = obscuring thông tin material.",
},
{
  "id": 4,
  "title": "The one-cent earnings target",
  "company": "CareHealth Services",
  "difficulty": "Hard",
  "primary": "Materiality — qualitative and contextual",
  "primaryKey": "materiality",
  "cf": "CF.2.11",
  "distractors": ["Neutrality only", "Free from error only", "Cost constraint", "Comparability"],
  "keywords": ["material", "eps", "ngưỡng", "qualitative", "1%", "forecast", "nature"],
  "scenario": "CareHealth Services has 100 million ordinary shares in issue and is closely followed by three sell-side analysts, all of whom published a 20X6 EPS forecast of CU0.24. Before the last accounting adjustment, profit for the year was CU23.4 million, producing EPS of CU0.234. On 30 December, without any new legal advice or court development, management reversed a CU600,000 accrual for legal expenses that had been supported by an external counsel letter dated 15 December. Profit increased to CU24.0 million and EPS to CU0.240. The CU600,000 amount represents 0.3 per cent of revenue and 0.2 per cent of total assets. Management’s closing paper concludes that the reversal is immaterial because both ratios are below the company’s informal 1 per cent threshold, and that no separate disclosure is required.",
  "model": "Đặc tính quyết định: Materiality như khía cạnh entity-specific của Relevance — CF.2.11. Không có ngưỡng % thống nhất. Nature hoặc magnitude. CU600,000 nhỏ so với doanh thu nhưng đưa EPS đúng forecast, không có bằng chứng mới, có thể thay đổi quyết định. Đảo ngược không căn cứ còn vi phạm free from error / neutrality. “Dưới 1% = immaterial” là sai.",
},
{
  "id": 5,
  "title": "An estimate that later proves wrong",
  "company": "FreshMart Co.",
  "difficulty": "Hard",
  "primary": "Free from error — outcome is not an error",
  "primaryKey": "free from error",
  "cf": "CF.2.18–2.19",
  "distractors": ["Relevance", "Neutrality", "Comparability", "Timeliness"],
  "keywords": ["estimate", "không phải error", "change in estimate", "IAS 8", "free from error", "quy trình"],
  "scenario": "FreshMart Co. sells consumer appliances with a two-year warranty. In preparing the 20X4 financial statements the company estimated warranty costs at CU3.0 million, using five years of claims history, current failure rates and the product mix then in the market. The estimate was described in the notes as an estimate and the method was explained. During 20X6 an unexpected defect in a component supplied by a new vendor caused actual cash payments on the 20X4 cohort to reach CU4.2 million. A shareholder has written to the board arguing that the CU3 million figure was incorrect and the original financial statements therefore did not faithfully represent the company’s obligations. Management is considering whether the 20X4 statements should be restated as an error or whether 20X6 should simply absorb a change in estimate.",
  "model": "Đặc tính quyết định: Free from error — CF.2.18–2.19. Faithful representation không có nghĩa chính xác tuyệt đối. Nếu quy trình phù hợp và dùng bằng chứng lúc đó, đây không phải error mà là thay đổi ước tính (IAS 8). Defect bất ngờ là thông tin mới. Error chỉ khi dùng dữ liệu sai, bỏ qua thông tin đã có, hoặc bias.",
},
{
  "id": 6,
  "title": "A complete number with incomplete depiction",
  "company": "NorthPeak Mining",
  "difficulty": "Medium-Hard",
  "primary": "Completeness",
  "primaryKey": "completeness",
  "cf": "CF.2.13–2.14",
  "distractors": ["Verifiability", "Understandability only", "Materiality", "Cost constraint"],
  "keywords": ["complete", "thuyết minh", "discount", "sensitivity", "giả định", "một dòng"],
  "scenario": "NorthPeak Mining recognises a decommissioning provision of CU60 million at 31 December 20X6. The figure is the present value of estimated rehabilitation cash flows of CU110 million expected in fifteen years, discounted at 4.1 per cent, and assumes that current environmental statutes will remain unchanged. The site is NorthPeak’s only producing mine and the provision is material to both liabilities and gearing covenants. On the face of the statement of financial position and in the notes the company presents a single line: “Decommissioning provision CU60 million.” There is no description of timing, undiscounted cash flows, the discount rate, sensitivity to a change in the rate or in closure date, or the possibility that forthcoming regulation would increase the scope of work. Management considers the line item complete because the amount has been recognised in full.",
  "model": "Đặc tính quyết định: Completeness — CF.2.13–2.14. Ghi nhận số không thay cho mô tả đầy đủ: bản chất, ý nghĩa của số (present value), giả định then chốt, độ nhạy. Không cần dump spreadsheet kỹ sư. Verifiability và understandability bị kéo theo, nhưng thiếu thông tin cần thiết trước hết là không complete.",
},
{
  "id": 7,
  "title": "A new CEO’s clean-up year",
  "company": "Apex Retail Group",
  "difficulty": "Hard",
  "primary": "Neutrality — big-bath earnings management",
  "primaryKey": "neutrality",
  "cf": "CF.2.16–2.17",
  "distractors": ["Prudence", "Completeness", "Timeliness", "Comparability"],
  "keywords": ["big bath", "neutral", "overstate", "không phải prudence", "buffer", "present obligation"],
  "scenario": "Apex Retail Group appointed a new chief executive on 1 November 20X6. In December the company recognised a “strategic restructuring provision” of CU45 million, converting a draft profit of CU12 million into a reported loss of CU33 million. Working papers split the CU45 million as follows: CU8 million of redundancy costs for which communication to those affected had occurred before 31 December and a present obligation therefore existed; CU22 million relating to store closures on which the board will vote only in March 20X7; and CU15 million labelled internally as a “buffer for surprises so that 20X7 starts fresh.” In the January results call the CEO described 20X6 as “a transition year” and said that 20X7 guidance had been set at a level the company could “comfortably beat.” No analysis of the three components is provided in the financial statements.",
  "model": "Đặc tính quyết định: Neutrality. Prudence không cho phép overstate liabilities. Chỉ khoảng CU8m là nghĩa vụ hiện tại. Phần còn lại là kế hoạch tương lai và buffer — big bath. 20X6 quá bi quan, 20X7 quá lạc quan. Không gọi đây là conservative/prudence.",
},
{
  "id": 8,
  "title": "A one-year change in the inventory formula",
  "company": "Helio Electronics",
  "difficulty": "Hard",
  "primary": "Comparability — consistency is the means",
  "primaryKey": "comparability",
  "cf": "CF.2.24–2.29",
  "distractors": ["Understandability", "Cost constraint", "Materiality", "Timeliness"],
  "keywords": ["comparab", "consistency", "FIFO", "restat", "không phải uniformity"],
  "scenario": "Helio Electronics has measured inventories at FIFO cost for twelve consecutive years. Input prices rose sharply in 20X6. Management changed to weighted-average cost for 20X6 only, reducing cost of sales by CU18 million compared with FIFO and lifting profit just above the threshold in a bank covenant. The notes state that the change “better reflects the physical flow of goods.” Warehouse scan data continue to show that the oldest batches are issued first. The finance director has already minuted an intention to revert to FIFO in 20X7 “once prices stabilise.” Comparative figures for 20X5 have not been restated and no pro forma FIFO result for 20X6 is given. Management argues that an entity is free to select an acceptable cost formula each year.",
  "model": "Đặc tính quyết định: Comparability — CF.2.24–2.29. Consistency là phương tiện, không phải QC. Thay đổi một năm, lý do không khớp physical flow, có động cơ covenant, không restatement. Alternative methods diminish comparability. Cũng tổn hại faithful representation.",
},
{
  "id": 9,
  "title": "Statements authorised nine months late",
  "company": "Harbor Ports Ltd",
  "difficulty": "Medium",
  "primary": "Timeliness",
  "primaryKey": "timeliness",
  "cf": "CF.2.33",
  "distractors": ["Relevance as primary", "Faithful representation", "Verifiability", "Completeness"],
  "keywords": ["timely", "trễ", "enhancing", "chín tháng", "delay"],
  "scenario": "Harbor Ports Ltd’s reporting date is 31 December 20X6. Complete IFRS financial statements were authorised for issue only on 28 September 20X7. Management attributes the delay to conversion of a new ERP system and to a prolonged dispute with the predecessor auditor. In April 20X7, while the 20X6 report was still unpublished, Harbor privately refinanced a CU200 million facility; lenders later told the board they would have priced the facility differently had they seen the overdue statements. Two listed competitors released 20X6 results in March 20X7 and were subsequently acquired at a premium. An institutional holder that sold its entire position in May 20X7 has written that the information, when it finally appeared, was no longer capable of influencing the decision already taken.",
  "model": "Đặc tính quyết định: Timeliness — CF.2.33. Enhancing, không phải fundamental. Thông tin 9 tháng sau khóa sổ kém khả năng ảnh hưởng quyết định (tái tài trợ, bán cổ phiếu). Relevance tiềm năng vẫn còn nhưng bị weakening. Timeliness không cứu được thông tin sai (CF.2.37).",
},
{
  "id": 10,
  "title": "Too complex to disclose",
  "company": "NovaBank",
  "difficulty": "Hard",
  "primary": "Understandability does not justify omission",
  "primaryKey": "understandability",
  "cf": "CF.2.34–2.36",
  "distractors": ["Cost constraint", "Materiality", "Timeliness", "Comparability"],
  "keywords": ["understand", "không được loại", "complex", "complete", "omit"],
  "scenario": "NovaBank holds a portfolio of structured credit derivatives with a carrying amount of CU1.1 billion, equal to 9 per cent of total assets. Fair value is produced by an internal model that uses fourteen unobservable inputs. The chief financial officer has instructed the reporting team to omit any narrative description of the portfolio from the statement of financial position and from the notes, leaving only a single line “other financial assets.” The instruction memo states that even sophisticated users will not understand the model, including it would make the financial statements unreadable, and understandability requires us to keep the report simple. No sensitivity table, no input ranges and no description of the risks remain in the authorised set.",
  "model": "Đặc tính quyết định: Understandability — nhưng CF.2.35 cấm loại thông tin phức tạp. Loại ra làm incomplete và có thể misleading. User được giả định có hiểu biết hợp lý. Cách đúng: phân loại, mô tả súc tích, độ nhạy Level 3 — không xóa sổ. Completeness cũng bị phá.",
},
{
  "id": 11,
  "title": "A Level 3 fair value without inputs",
  "company": "Lumen Ventures",
  "difficulty": "Hard",
  "primary": "Verifiability and completeness of a Level 3 estimate",
  "primaryKey": "verifiability",
  "cf": "CF.2.30–2.32",
  "distractors": ["Free from error only", "Relevance", "Comparability", "Timeliness"],
  "keywords": ["verif", "range", "input", "indirect", "uncertainty", "CF.2.22"],
  "scenario": "Lumen Ventures measures its 22 per cent holding in an unlisted investee at fair value of CU87 million at 31 December 20X6. The amount comes from a proprietary discounted-cash-flow model maintained by an external consultant. The notes contain one sentence: “Fair value is based on a discounted cash-flow model.” No unobservable inputs, no discrete scenarios, no range and no sensitivity to revenue growth or discount rate are disclosed. Two valuation specialists engaged by the audit committee, using different but reasonable assumptions, arrived at CU41 million and CU120 million respectively. Management has refused to disclose that range on the grounds that IFRS requires a single point estimate to be recognised and presenting a range would confuse users.",
  "model": "Đặc tính quyết định: Verifiability (CF.2.30–2.32) kết hợp Completeness. Có thể verify một khoảng, không bắt buộc một điểm. Không có input thì không indirect-verify được. CF.2.22: ước tính bất định vẫn useful nếu mô tả rõ uncertainty. Khác biệt giữa hai chuyên gia không tự thành error.",
},
{
  "id": 12,
  "title": "Cash presented net of an unrelated overdraft",
  "company": "Orion Logistics",
  "difficulty": "Medium-Hard",
  "primary": "Faithful representation — offsetting unlike items",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12 / CF.2.27",
  "distractors": ["Materiality", "Understandability as primary", "Timeliness", "Cost constraint"],
  "keywords": ["offset", "set-off", "gross", "thấu chi", "faithful", "unlike"],
  "scenario": "Orion Logistics presents a single line “Cash and cash equivalents CU2 million” as the first item of current assets. Note 17, on page 64 of the annual report, reveals that the group holds CU48 million of demand deposits at Bank A and a CU46 million overdraft at Bank B. The two facilities are in different jurisdictions, the overdraft is repayable on demand, and the group has neither a legally enforceable right of set-off nor an intention to settle net. Management’s paper to the audit committee argues that the net figure of CU2 million better shows the liquidity available to the group as a whole and is more understandable than two large gross amounts that largely cancel. Covenant tests and the statement of cash flows are also prepared from the net number.",
  "model": "Đặc tính quyết định: Faithful representation. Tiền và thấu chi không có quyền bù trừ là hai hiện tượng khác nhau. Netting làm unlike things look alike (CF.2.27). Understandability không được đánh đổi FR (CF.2.37). Trình bày groos: cash CU48m và overdraft CU46m.",
},
{
  "id": 13,
  "title": "An internally generated brand recognised at strategic value",
  "company": "Aura Cosmetics",
  "difficulty": "Very hard",
  "primary": "Trade-off: relevance versus faithful representation",
  "primaryKey": "trade-off",
  "cf": "CF.2.20–2.22",
  "distractors": ["Relevance only", "Completeness only", "Comparability", "Prudence"],
  "keywords": ["trade-off", "IAS 38", "uncertainty", "không ghi nhận", "thuyết minh", "2.22"],
  "scenario": "Aura Cosmetics has built a consumer brand over twenty years of advertising and product development. In 20X6 management wishes users to see the real value of the business and has recognised an internally generated brand asset of CU400 million, with a matching gain in profit for the year. The CU400 million is the midpoint of a marketing consultant’s range of CU150 million to CU900 million. There is no active market for the brand and no recent orderly transaction. IAS 38 would prohibit recognition of internally generated brands. The chief financial officer has told the auditors that the Conceptual Framework prefers the most relevant information, brand value is the most relevant information about our resources, and a Framework-based treatment should override a restrictive standard. Neither the range nor the estimation process is described in the notes.",
  "model": "Đặc tính quyết định: áp dụng đồng thời Relevance và Faithful representation — CF.2.20–2.22. Brand tự tạo relevant nhưng measurement uncertainty quá cao (CU150–900m) nên không sufficiently faithful. Framework không override IAS 38. Kênh đúng: thuyết minh, không đưa CU400m vào P/L. Relevance không thắng một mình.",
},
{
  "id": 14,
  "title": "Interest paid reclassified every year",
  "company": "Riverbond Plc",
  "difficulty": "Medium-Hard",
  "primary": "Comparability of cash-flow classification",
  "primaryKey": "comparability",
  "cf": "CF.2.26–2.29",
  "distractors": ["Timeliness", "Materiality", "Neutrality", "Cost constraint"],
  "keywords": ["comparab", "IAS 7", "operating", "consistency", "restat"],
  "scenario": "Riverbond Plc presents a statement of cash flows under IAS 7. Interest paid of approximately CU40 million a year was classified as an operating outflow in 20X4, as a financing outflow in 20X5, and again as an operating outflow in 20X6. Each year’s notes assert that the classification better reflects the nature of the entity’s financing. Reported operating cash flow for 20X6 is CU90 million after adding back the CU40 million of interest; under the 20X5 policy the same year’s operating cash flow would have been CU50 million. Sell-side models treat operating cash flow as the starting point for valuation. Comparatives have not been restated for the latest change. Management notes that IAS 7 permits a choice and therefore considers consistency a matter of preference rather than of useful information.",
  "model": "Đặc tính quyết định: Comparability. IAS 7 cho chọn không xóa yêu cầu nhất quán intra-entity. Nhảy qua lại làm like cash flows trông khác. Thuyết minh giúp tái phân loại một phần (CF.2.38) nhưng không phục hồi hết time-series. Chọn một chính sách và restatement comparatives.",
},
{
  "id": 15,
  "title": "Going-concern doubts omitted because nothing is booked",
  "company": "Cedar Pharma",
  "difficulty": "Hard",
  "primary": "Relevance and completeness of the going-concern depiction",
  "primaryKey": "relevance",
  "cf": "CF.2.6 / Ch.3",
  "distractors": ["Prudence", "Verifiability", "Comparability", "Free from error"],
  "keywords": ["going concern", "relevant", "thuyết minh", "40%", "im lặng", "predictive"],
  "scenario": "Cedar Pharma’s principal product, representing 70 per cent of revenue, is under a regulator’s safety review. Two independent counsel have advised the board that there is a 40 per cent probability the marketing licence will be withdrawn within twelve months of 31 December 20X6, in which case the company would enter an orderly wind-down. Inventories and specialised plant would realise substantially less than their going-concern carrying amounts. Management has prepared the 20X6 financial statements on a going-concern basis with no emphasis of matter, no note on the review and no description of the alternative outcome. The board paper states that no present obligation has arisen, no asset is impaired if going concern is assumed, and therefore there is nothing relevant to report. Disclosure would panic the market and destroy enterprise value.",
  "model": "Đặc tính quyết định: Relevance (và completeness của depiction về entity). 40% khả năng chấm dứt mô hình kinh doanh capable of making a difference dù chưa ghi impairment. Giả định going concern không được im lặng khi có nghi ngờ đáng kể. “Không panic thị trường” là thao túng neutrality.",
},
{
  "id": 16,
  "title": "Related-party rent described as arm’s length",
  "company": "Summit Foods",
  "difficulty": "Hard",
  "primary": "Faithful representation of related-party substance",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12 / CF.2.11",
  "distractors": ["Comparability", "Timeliness", "Understandability only", "Cost constraint"],
  "keywords": ["related", "arm’s", "nature", "phân phối", "faithful", "10 lần"],
  "scenario": "Summit Foods pays CU12 million a year to lease its central warehouse from a company owned by the chair’s family. Two independent appraisals obtained by the audit committee put market rent for an equivalent facility at CU1.2 million. Summit records the full CU12 million as operating rent. The related-party note consists of one sentence: “The Group leases warehousing from a related party on arm’s-length terms.” The note does not identify the related party, does not state the amount, and does not compare the terms with the market. The family company reports the CU12 million as ordinary rental income. Management considers the sentence sufficient because IAS 24 is a disclosure standard and the transaction has been recognised.",
  "model": "Đặc tính quyết định: Faithful representation kết hợp completeness và materiality theo nature. Gọi arm’s length khi bằng chứng cho thấy gấp 10 lần là mô tả sai. Phần CU10.8m có bản chất phân phối cho bên liên quan. Nature (related party) làm thông tin material dù có thể nhỏ so với tổng chi phí.",
},
{
  "id": 17,
  "title": "A write-down reversed to clear the bonus hurdle",
  "company": "Polar Outdoor",
  "difficulty": "Hard",
  "primary": "Neutrality and qualitative materiality",
  "primaryKey": "neutrality",
  "cf": "CF.2.15 / CF.2.11",
  "distractors": ["Comparability", "Timeliness", "Completeness only", "Understandability"],
  "keywords": ["bonus", "neutral", "đảo", "material", "NRV", "target"],
  "scenario": "Polar Outdoor’s executive bonus plan pays if operating profit exceeds CU50 million. On 20 December 20X6 a year-end net-realisable-value review of seasonal inventory, supported by subsequent-order data and markdown plans, indicated a write-down of CU3.2 million and a resulting profit of CU48.1 million. On 28 December management reassessed fashion-season demand and reversed CU2.0 million of that write-down, lifting profit to CU50.1 million. Internal email circulating the same day reads: “We only need CU1.9 million more. The goods can always be discounted in January.” Sales of the same stock in January 20X7 realised amounts consistent with the original 20 December assessment. No mention of the reversal, the bonus plan or the January evidence appears in the financial statements.",
  "model": "Đặc tính quyết định: Neutrality; materiality theo ngữ cảnh bonus. NRV ban đầu có bằng chứng; đảo ngược không có bằng chứng mới, chỉ có target thưởng. CU2m làm thay đổi kết quả thưởng nên qualitative material. Quy trình ước tính bị áp dụng sai nên cũng không free from error.",
},
{
  "id": 18,
  "title": "Two identical ships, two opposite treatments",
  "company": "BlueKeel Shipping",
  "difficulty": "Hard",
  "primary": "Comparability plus substance over form",
  "primaryKey": "comparability",
  "cf": "CF.2.12 / CF.2.27",
  "distractors": ["Timeliness", "Materiality", "Cost constraint", "Understandability only"],
  "keywords": ["like things", "substance", "lease", "comparab", "nhãn"],
  "scenario": "BlueKeel Shipping took delivery of two identical container vessels in the same week, from the same lessor, on contracts with the same term, the same residual-value guarantee and the same pattern of payments. Ship A’s contract is headed “Lease” and is recognised on the statement of financial position. Ship B’s contract is headed “Capacity purchase agreement,” never uses the word lease, and does not transfer legal title; management has left Ship B off the statement of financial position and expensed the payments as they fall due. The two arrangements give BlueKeel the right to direct use of each vessel for the same period and require BlueKeel to absorb substantially the same residual-value risk. Management told the auditors that both treatments are allowed by the documents and that users can reconstruct comparability from forty pages of notes.",
  "model": "Đặc tính quyết định: Comparability gắn với Faithful representation của cùng một hiện tượng. Hai tàu đồng nhất = like things must look alike. Nhãn pháp lý không đổi substance. Thuyết minh bù một phần (CF.2.38) không thay nhận diện nhất quán. Enhancing không cứu unfaithful depiction của Ship B.",
},
{
  "id": 19,
  "title": "A policy of always taking the worst number",
  "company": "Stonebridge Construction",
  "difficulty": "Very hard",
  "primary": "Prudence is not asymmetry or maximum pessimism",
  "primaryKey": "neutrality",
  "cf": "CF.2.16–2.17",
  "distractors": ["Relevance", "Completeness", "Comparability", "Timeliness"],
  "keywords": ["prudence", "không bất đối xứng", "neutral", "virtually certain", "mút biên"],
  "scenario": "Stonebridge Construction’s audit committee adopted a written “prudence policy” in 20X6. For every uncertain asset the company must recognise the lowest amount in the reasonably possible range; for every uncertain liability it must recognise the highest amount; contingent assets are never recognised, even when inflow is assessed as virtually certain. Applying the policy, a lawsuit whose most likely outcome is CU6 million and whose reasonably possible range is CU4 million to CU9 million has been recorded at CU9 million. A contractual compensation claim that counsel describes as virtually certain of collection at CU5 million has been omitted entirely. The committee’s covering note states that the policy implements the Framework’s concept of prudence and protects creditors, and that asymmetry is a virtue of useful financial information.",
  "model": "Đặc tính quyết định: hiểu đúng Prudence trong Neutrality — CF.2.16–2.17. Prudence không hàm ý bất đối xứng. Chọn systematically mút biên = bias. Bỏ qua inflow virtually certain là understatement of assets. Mục tiêu BCTC đa mục đích không phải bảo vệ chủ nợ bằng số lệch. Ghi lawsuit khoảng CU6m; ghi nhận compensation CU5m nếu virtually certain.",
},
{
  "id": 20,
  "title": "A quantitatively small fraud with a large story",
  "company": "Meadow Dairy",
  "difficulty": "Hard",
  "primary": "Materiality by nature, not magnitude",
  "primaryKey": "materiality",
  "cf": "CF.2.11",
  "distractors": ["Cost constraint", "Timeliness", "Comparability", "Understandability"],
  "keywords": ["nature", "material", "fraud", "omitting", "obscur", "regulator"],
  "scenario": "Internal audit at Meadow Dairy found that a regional manager diverted CU180,000 of company cash over two years. The amount is 0.04 per cent of group revenue and 0.7 per cent of profit and has since been repaid in full. The scheme was effected by falsifying quality certificates for milk supplied under a public-school nutrition contract. A food-safety regulator has opened a file; counsel cannot yet estimate a fine. Management has omitted any reference to the matter from the 20X6 financial statements and from the governance report, arguing that the amount is quantitatively immaterial, has been corrected, and that a fine is not probable and would be small. No provision, no contingent-liability note and no description of the regulatory inquiry are included.",
  "model": "Đặc tính quyết định: Materiality — nature or magnitude or both — CF.2.11. Gian lận, hàng giả cho trường học, điều tra cơ quan quản lý: bản chất có thể ảnh hưởng quyết định dù số nhỏ. Omitting và obscuring nằm trong định nghĩa. Hoàn trả không xóa hiện tượng đã xảy ra. Không áp dụng ngưỡng 5% máy móc.",
},
{
  "id": 21,
  "title": "A DCF that nobody else can rerun",
  "company": "Atlas Renewables",
  "difficulty": "Medium-Hard",
  "primary": "Verifiability of an undocumented model",
  "primaryKey": "verifiability",
  "cf": "CF.2.30–2.32",
  "distractors": ["Timeliness", "Relevance only", "Prudence", "Comparability"],
  "keywords": ["verif", "macro", "giả định", "indirect", "replicate"],
  "scenario": "Atlas Renewables measures a long-term power-purchase contract at fair value using a discounted-cash-flow model. The model resides on a single analyst’s laptop, contains undocumented macros, and includes an undocumented “experience adjustment” of plus 12 per cent to forecast generation volume. The notes disclose the resulting fair value and the discount rate and nothing else. When the engagement quality reviewer asked two other members of the finance team to replicate the year-end number from the same contractual inputs, both failed. Management’s response is that verifiability is unnecessary because fair value is an estimate and estimates are never exact, and that publishing the macros would reveal commercially sensitive assumptions.",
  "model": "Đặc tính quyết định: Verifiability — CF.2.30–2.32. Ước tính vẫn cần verifiable. Indirect verification = kiểm tra input + tính lại. Macro không tài liệu + experience adjustments không mô tả → thất bại. Với thông tin hướng tương lai phải công bố giả định và phương pháp (CF.2.32).",
},
{
  "id": 22,
  "title": "Copying peers in order to be comparable",
  "company": "Nimbus Software",
  "difficulty": "Very hard",
  "primary": "Comparability is not uniformity or copying a misrepresentation",
  "primaryKey": "comparability",
  "cf": "CF.2.27–2.28",
  "distractors": ["Timeliness", "Materiality", "Understandability", "Cost constraint"],
  "keywords": ["uniformity", "principal", "substance", "không copy", "like things"],
  "scenario": "Nimbus Software sells subscriptions to a platform that it develops, hosts and controls. It sets the price, is the contracting party with the customer and is responsible for service credits. Three larger listed peers report revenue on a net commission basis and therefore display higher percentage margins on a smaller top line. Nimbus’s chief financial officer has proposed switching Nimbus to the same net basis to improve comparability with the peer group and to help investors value us on the same multiple. Legal analysis of Nimbus’s own contracts continues to conclude that Nimbus is the principal. No change in the underlying economics is alleged.",
  "model": "Đặc tính quyết định: Comparability ≠ uniformity — CF.2.27–2.28. Nimbus là principal; ghi net sẽ làm unlike things look alike nếu peers thật sự là agent, hoặc nhân rộng unfaithful nếu peers cũng là principal. Enhancing không được dùng để chọn mô tả không trung thực. Giữ gross + thuyết minh để user tự so sánh.",
},
{
  "id": 23,
  "title": "Two-page financial statements of a listed group",
  "company": "Helix Telecom",
  "difficulty": "Medium-Hard",
  "primary": "Understandability abused against completeness",
  "primaryKey": "understandability",
  "cf": "CF.2.34–2.35",
  "distractors": ["Timeliness only", "Verifiability", "Prudence", "Free from error"],
  "keywords": ["concise", "obscur", "complete", "notes", "understand"],
  "scenario": "Helix Telecom is listed and operates in nineteen countries. For 20X6 it published “concise financial statements” of two pages: a highly aggregated statement of profit or loss and a statement of financial position containing seven lines. Almost all note disclosures required by IFRS have been moved to a password-protected data room described as available on request to serious investors. Segment information, maturity analyses, related-party detail and measurement uncertainties are therefore absent from the document filed with the regulator. Management cites the Conceptual Framework: classifying and presenting information clearly and concisely makes it understandable; users drown in notes. The group is not a small entity and has not obtained any exemption from full IFRS presentation.",
  "model": "Đặc tính quyết định: Understandability không cho phép cắt thông tin cần thiết — CF.2.34–2.35. Concise là cách trình bày, không phải xóa hiện tượng. Data room làm obscuring (CF.2.11). Cost constraint do IASB cân khi viết chuẩn mực, listed group không tự miễn notes. Aggregation quá mức làm unlike items look alike.",
},
{
  "id": 24,
  "title": "A factory destroyed after the reporting date",
  "company": "Ironclad Manufacturing",
  "difficulty": "Hard",
  "primary": "Relevance of a non-adjusting subsequent event",
  "primaryKey": "relevance",
  "cf": "CF.2.6–2.8",
  "distractors": ["Comparability as primary", "Free from error", "Neutrality", "Cost constraint"],
  "keywords": ["subsequent", "non-adjusting", "thuyết minh", "IAS 10", "predictive", "cháy"],
  "scenario": "Ironclad Manufacturing’s reporting date is 31 December 20X6 and the financial statements were authorised on 28 February 20X7. On 5 January 20X7 a fire destroyed the company’s only plant. The carrying amount of the plant at 31 December was CU70 million, equal to 31 per cent of total assets. Insurance coverage is disputed and recovery is uncertain. Production has stopped and alternative capacity cannot be contracted before the third quarter of 20X7. Management has neither adjusted the 20X6 amounts nor disclosed the fire. The paper to the board states that the fire occurred after the reporting date, it is a 20X7 event, and recording or even highlighting it in the 20X6 statements would mix periods and destroy comparability.",
  "model": "Đặc tính quyết định: Relevance (predictive value). Non-adjusting subsequent event (IAS 10): không sửa số 20X6 nhưng phải thuyết minh nếu material. Im lặng đến 28/2 là obscuring. Comparability không bị phá bởi một note; ngược lại note ngăn user suy ra sai rằng năng lực sản xuất còn nguyên.",
},
{
  "id": 25,
  "title": "Too costly to count 40 per cent of assets",
  "company": "Granite Materials",
  "difficulty": "Hard",
  "primary": "Cost constraint misapplied by an individual entity",
  "primaryKey": "cost constraint",
  "cf": "CF.2.39–2.43",
  "distractors": ["Timeliness", "Understandability", "Prudence", "Comparability"],
  "keywords": ["cost constraint", "IASB", "không miễn trừ", "kiểm kê", "11%"],
  "scenario": "Granite Materials holds stockpiles of crushed stone at forty sites. Inventories represent 40 per cent of total assets. For 20X6 management cancelled the year-end physical count at thirty-one sites and rolled quantities forward from the 20X4 count, adjusted only for recorded production and despatch. The board paper invokes the Conceptual Framework’s cost constraint: counting every pile would cost CU1.2 million in surveys; users would not pay more for our shares merely because we counted rocks. A sample count completed at the remaining nine sites found quantities 11 per cent below the rolled-forward book. No adjustment was made for the uncounted sites and no description of the limitation appears in the notes.",
  "model": "Đặc tính quyết định: Cost constraint bị áp dụng sai — CF.2.39–2.43. Board cân cost/benefit khi xây chuẩn mực, không phải từng entity tự loại yêu cầu. Mẫu đã sai 11% → số không còn faithful / free from error. Phải kiểm kê hoặc phương pháp thay thế đáng tin, và thuyết minh limitation.",
},
{
  "id": 26,
  "title": "A stale related-party price versus a very wide DCF",
  "company": "Quartz Biologics",
  "difficulty": "Very hard",
  "primary": "CF.2.22 trade-off between relevance and faithful representation",
  "primaryKey": "trade-off",
  "cf": "CF.2.21–2.22",
  "distractors": ["Comparability", "Timeliness", "Prudence", "Materiality only"],
  "keywords": ["trade-off", "2.22", "range", "uncertainty", "relevant", "faithful"],
  "scenario": "Quartz Biologics holds a 12 per cent interest in an unlisted gene-therapy company. At 31 December 20X6 two candidate measurements exist. The first is the price in the last transaction, eighteen months earlier, of CU22 million; that transaction was between related founders and no subsequent arm’s-length trade has occurred. The second is a current discounted-cash-flow valuation prepared by Quartz, which produces a range of CU19 million to CU140 million depending on FDA-approval scenarios; management’s preferred point within that range is CU95 million. The chief financial officer argues that the Framework requires the most relevant information and that the eighteen-month price is stale, so CU95 million must be booked. The engagement partner argues that CU95 million cannot be a sufficiently faithful representation and that Quartz should either retain CU22 million or not remeasure at all.",
  "model": "Đặc tính quyết định: trade-off Relevance vs Faithful representation — CF.2.21–2.22. Most relevant có lẽ là ước tính hiện tại, không phải giá 18 tháng bên liên quan. Nhưng CU95m trong range CU19–140m, chọn điểm vì management, uncertainty cực cao. Useful nhất thường là ước tính kèm mô tả uncertainty / công bố range, không phải một điểm im lặng cũng không neo mãi CU22m như current value.",
},
{
  "id": 27,
  "title": "Adjusted EBITDA on the face, IFRS profit in a note",
  "company": "Pulse Fitness",
  "difficulty": "Hard",
  "primary": "Neutrality in presentation of performance",
  "primaryKey": "neutrality",
  "cf": "CF.2.15",
  "distractors": ["Timeliness", "Verifiability", "Cost constraint", "Prudence"],
  "keywords": ["EBITDA", "emphasise", "neutral", "IFRS 18", "de-emphas"],
  "scenario": "Pulse Fitness presents “Management operating profit (adjusted EBITDA)” in bold type as the final line of the statement of profit or loss. IFRS profit for the year is CU12 million. Adjusted EBITDA is CU41 million after adding back share-based payments, a restructuring programme, an amount described as “normalised rent” and “non-cash depreciation.” A reconciliation appears in Note 28. Every chart in the front half of the annual report, and the first page of the results announcement, uses only adjusted EBITDA. Management’s rationale is that users find EBITDA more relevant than IFRS profit and relevance comes first. No equally prominent presentation of IFRS profit is given on the face of the primary statements.",
  "model": "Đặc tính quyết định: Neutrality trong lựa chọn và trình bày — CF.2.15. Không nhấn/làm mờ để hướng phản ứng của user. Đưa adjusted EBITDA thành dòng cuối đậm, chôn IFRS profit là de-emphasising. Relevance không đứng trên FR (CF.2.20). MPM hữu ích nếu minh bạch, không át via, reconcile rõ.",
},
{
  "id": 28,
  "title": "One line for every obligation that could sink the company",
  "company": "HarborChem",
  "difficulty": "Hard",
  "primary": "Completeness of aggregated provisions",
  "primaryKey": "completeness",
  "cf": "CF.2.14 / CF.2.11",
  "distractors": ["Timeliness", "Comparability only", "Free from error only", "Cost constraint"],
  "keywords": ["aggregat", "complete", "obscur", "range", "investigation", "unlike"],
  "scenario": "HarborChem presents a single line “Provisions CU88 million.” The underlying ledger comprises environmental remediation of CU18 million, warranties of CU7 million, onerous contracts of CU9 million, restructuring of CU5 million, and a competition-law investigation that counsel says could produce a fine anywhere between nil and CU400 million, of which management has booked CU12 million at the lower end of its own range. A further CU37 million is classified as “other,” of which CU30 million is an unlabelled indemnity given when a subsidiary was sold. No breakdown, no ranges, no sensitivity and no description of the investigation or the indemnity appear in the notes. Management considers the total material and therefore sufficient.",
  "model": "Đặc tính quyết định: Completeness kết hợp materiality-as-obscuring. Điều tra CU0–400m ghi CU12m rồi trộn với bảo hành là unlike things look alike. Predictive value mất. Phải tách các hiện tượng khác bản chất và công bố range của investigation + indemnity. Ghi nhận tổng không thay completeness của mô tả.",
},
{
  "id": 29,
  "title": "Bill-and-hold revenue that never left the warehouse",
  "company": "Vertex Equipment",
  "difficulty": "Hard",
  "primary": "Faithful representation — control has not passed",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12 / CF.2.20",
  "distractors": ["Timeliness", "Comparability", "Understandability", "Cost constraint"],
  "keywords": ["control", "bill-and-hold", "không doanh thu", "substance", "return"],
  "scenario": "On 29 December 20X6 Vertex Equipment recognised CU35 million of revenue on a bill-and-hold arrangement with a distributor. The goods remain in Vertex’s warehouse. The distributor has a unilateral right to return any unsold items until 30 June 20X7, has not paid, and has not entered a separate storage agreement. Vertex continues to insure the goods and to control access to the bay in which they are stored. Without this transaction Vertex would have missed published earnings guidance by 6 per cent. Management’s position is that a legal invoice has been issued so the sale exists; users want to see the order book converted into revenue this year; that information has confirmatory value against our guidance.",
  "model": "Đặc tính quyết định: Faithful representation of control/substance, không phải legal invoice. Hàng chưa chuyển giao kiểm soát: còn kho người bán, quyền trả hàng, chưa trả tiền. Hiện tượng là inventory + executory arrangement. Confirmatory value nhân tạo không cứu mô tả không faithful. Thông tin backlog ở thuyết minh, không trên dòng revenue.",
},
{
  "id": 30,
  "title": "Four items and a list of every characteristic",
  "company": "MultiSignal Holdings",
  "difficulty": "Very hard",
  "primary": "Hierarchy: fundamental first, then enhancing, then cost",
  "primaryKey": "hierarchy",
  "cf": "CF.2.21 / CF.2.37",
  "distractors": ["Always materiality", "Always prudence", "Always comparability", "Cost constraint always wins"],
  "keywords": ["hierarchy", "quyết định", "fundamental", "enhancing", "(i)", "(iv)", "neutrality"],
  "scenario": "MultiSignal Holdings is closing its 20X6 report. Four unresolved items arrived on the same afternoon. First, a software implementation error double-counted cash by CU4 million for two weeks in December; the error was found during the audit and reversed before authorisation. Second, the board had publicly promised users a climate-related sensitivity analysis in the 20X6 statements; the model is unfinished and management proposes to issue the statements on time in February without that analysis. Third, a larger listed rival applies an unusual revenue cut-off; the commercial director wants MultiSignal to adopt the same cut-off so investors can compare us, although MultiSignal’s contracts transfer control at a different point. Fourth, a Level 3 biological asset can be supported only as a wide range; management wants the top of the range recognised in order to remain inside a gearing covenant. The technical team has written every qualitative characteristic next to every item and cannot agree which characteristic actually decides each issue.",
  "model": "Đặc tính quyết định của cả case: xếp tầng QC. (i) Free from error — đã sửa trước ban hành, depiction cuối faithful. (ii) Relevance + completeness của thông tin đã hứa, không phải timeliness. (iii) Faithful representation thắng comparability with rival (CF.2.37). (iv) Neutrality (chọn mút trên vì covenant) là quyết định, không chỉ measurement uncertainty. Đừng liệt kê hết QC; chỉ ra QC quyết định từng mục.",
},
]

out = pathlib.Path("/workspace/src/data/issues.ts")
out.write_text(
    "export type Issue = {\n"
    "  id: number;\n"
    "  title: string;\n"
    "  company: string;\n"
    "  difficulty: string;\n"
    "  primary: string;\n"
    "  primaryKey: string;\n"
    "  cf: string;\n"
    "  distractors: string[];\n"
    "  keywords: string[];\n"
    "  scenario: string;\n"
    "  model: string;\n"
    "};\n\nexport const ISSUES: Issue[] = "
    + json.dumps(ISSUES, ensure_ascii=False, indent=2)
    + ";\n\nexport function getIssue(id: number) {\n"
    "  return ISSUES.find((i) => i.id === id);\n"
    "}\n",
    encoding="utf-8",
)
print("wrote", out, "n=", len(ISSUES))
