# -*- coding: utf-8 -*-
ISSUES_21_30 = [
{
  "id": 21,
  "title": "Một mô hình DCF không ai khác chạy lại được",
  "company": "Atlas Renewables",
  "difficulty": "Trung bình–Khó",
  "primary": "Có thể kiểm chứng của mô hình không tài liệu",
  "primaryKey": "verifiability",
  "cf": "CF.2.30–2.32",
  "distractors": ["Kịp thời (Timeliness)", "Chỉ thích hợp (Relevance)", "Thận trọng (Prudence)", "Có thể so sánh (Comparability)"],
  "keywords": ["verif", "macro", "giả định", "indirect", "replicate", "kiểm chứng"],
  "scenario": "Atlas Renewables đo lường một hợp đồng mua điện dài hạn theo giá trị hợp lý bằng một mô hình chiết khấu dòng tiền. Mô hình nằm trên laptop của một chuyên viên duy nhất, chứa các macro không được tài liệu hóa, và gồm một “điều chỉnh kinh nghiệm” (experience adjustment) không được tài liệu hóa cộng 12% vào sản lượng phát dự báo. Thuyết minh công bố giá trị hợp lý ra được và lãi suất chiết khấu, không gì khác. Khi người soát xét chất lượng hợp đồng yêu cầu hai thành viên khác của phòng tài chính tái lập số cuối năm từ cùng các đầu vào hợp đồng, cả hai đều thất bại. Phản hồi của ban quản trị là verifiability không cần vì giá trị hợp lý là một ước tính và ước tính không bao giờ chính xác, và rằng công bố các macro sẽ tiết lộ các giả định nhạy cảm thương mại. Giám đốc tài chính viết thêm rằng  số FV “thích hợp nhất” cho user định giá PPA (Relevance); rằng giữ số cao hơn một chút là Prudence “đừng understate tài sản hợp đồng”; rằng hai công ty năng lượng ngang hàng cũng không công bố macro (Comparability); và rằng tài liệu hóa mô hình sẽ lùi phát hành ba tuần (Timeliness). Chi tiết nhiễu: Atlas đo một trang trại điện gió khác theo giá giao dịch gần nhất trên thị trường thứ cấp, thuyết minh đầy đủ Level 2; ban quản trị chỉ vào đó như “chính sách FV có thể kiểm chứng.” Email chuyên viên ngày 14 tháng 12: “Đừng đưa file cho EQCR. Plus 12% là để covenant DSCR đứng.”",
  "model": "Đặc tính quyết định: Verifiability — CF.2.30–2.32. Ước tính vẫn cần verifiable. Indirect verification = kiểm tra input + tính lại. Macro không tài liệu + experience adjustments không mô tả → thất bại. Với thông tin hướng tương lai phải công bố giả định và phương pháp (CF.2.32). Relevance của FV, prudence “đừng understate,” comparability với peer im lặng, timeliness là nhiễu. Trang trại Level 2 không cứu PPA không tái lập được. Cộng 12% vì covenant là bias, không phải estimate trung lập.",
},
{
  "id": 22,
  "title": "Sao chép đối thủ để được so sánh",
  "company": "Nimbus Software",
  "difficulty": "Rất khó",
  "primary": "Có thể so sánh không phải đồng nhất hay copy mô tả sai",
  "primaryKey": "comparability",
  "cf": "CF.2.27–2.28",
  "distractors": ["Kịp thời (Timeliness)", "Trọng yếu (Materiality)", "Dễ hiểu (Understandability)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["uniformity", "principal", "substance", "không copy", "like things", "so sánh"],
  "scenario": "Nimbus Software bán các thuê bao một nền tảng mà công ty tự phát triển, lưu trữ và kiểm soát. Công ty tự định giá, là bên ký hợp đồng với khách hàng và chịu trách nhiệm về tín dụng dịch vụ (service credits). Ba đối thủ niêm yết lớn hơn ghi nhận doanh thu trên cơ sở hoa hồng ròng (net commission) và do đó trình bày biên lợi nhuận % cao hơn trên một doanh thu nhỏ hơn. Giám đốc tài chính của Nimbus đã đề xuất chuyển Nimbus sang cùng cơ sở ròng để tăng khả năng so sánh với nhóm ngang hàng và để giúp nhà đầu tư định giá chúng ta theo cùng bội số. Phân tích pháp lý các hợp đồng của chính Nimbus vẫn kết luận rằng Nimbus là bên chính (principal). Không ai cho rằng bản chất kinh tế cơ bản đã thay đổi. Tờ trình nói ghi gross “làm user rối vì biên % thấp hơn peer” (Understandability); rằng chênh lệch gross/net 220 triệu CU “chỉ là trình bày, dưới 1% vốn hóa” nên Trọng yếu (Materiality) không đặt ra; rằng viết lại hệ thống billing tốn 1,4 triệu CU và ba tháng (Cost constraint, Timeliness). Chi tiết nhiễu: Nimbus có một mảng nhỏ marketplace chiếm 6% doanh thu, nơi công ty thật sự là agent; mảng đó đã ghi net đúng. Ban quản trị muốn “đồng bộ” toàn bộ sang net “cho một chính sách.” Email CFO ngày 9 tháng 11: “Peer multiple trên net revenue. Nếu ta ở gross, ta trông đắt. Chuyển.”",
  "model": "Đặc tính quyết định: Comparability ≠ uniformity — CF.2.27–2.28. Nimbus là principal; ghi net sẽ làm unlike things look alike nếu peers thật sự là agent, hoặc nhân rộng unfaithful nếu peers cũng là principal. Enhancing không được dùng để chọn mô tả không trung thực. Giữ gross + thuyết minh để user tự so sánh. Understandability, materiality “chỉ trình bày,” cost/timeliness là nhiễu. Mảng marketplace 6% (agent) đúng là net — không lan sang nền tảng tự host.",
},
{
  "id": 23,
  "title": "Báo cáo tài chính hai trang của một tập đoàn niêm yết",
  "company": "Helix Telecom",
  "difficulty": "Trung bình–Khó",
  "primary": "Dễ hiểu bị lạm dụng để chống đầy đủ",
  "primaryKey": "understandability",
  "cf": "CF.2.34–2.35",
  "distractors": ["Chỉ kịp thời (Timeliness)", "Có thể kiểm chứng (Verifiability)", "Thận trọng (Prudence)", "Không sai sót (Free from error)"],
  "keywords": ["concise", "obscur", "complete", "notes", "understand", "dễ hiểu"],
  "scenario": "Helix Telecom niêm yết và hoạt động tại mười chín quốc gia. Năm 20X6 công ty đã công bố “báo cáo tài chính súc tích” (concise financial statements) gồm hai trang: một báo cáo lãi lỗ gộp rất mạnh và một Bảng cân đối kế toán bảy dòng. Hầu hết các thuyết minh IFRS bắt buộc đã được chuyển vào một phòng dữ liệu có mật khẩu, được mô tả là sẵn cho các nhà đầu tư nghiêm túc khi yêu cầu. Thông tin bộ phận, phân tích đáo hạn, chi tiết bên liên quan và các bất định đo lường vì vậy vắng mặt trong hồ sơ nộp cơ quan quản lý. Ban quản trị viện dẫn Khung khái niệm: phân loại và trình bày thông tin rõ ràng, súc tích làm nó dễ hiểu; người sử dụng chết đuối trong thuyết minh. Tập đoàn không phải một đơn vị nhỏ và không được miễn trình bày IFRS đầy đủ. Giám đốc tài chính thêm rằng hai trang phát hành được sớm hơn ba tuần (Timeliness); rằng số trên mặt đã được kiểm toán nên Không sai sót (Free from error) và Có thể kiểm chứng (Verifiability) ổn; rằng lược note là Prudence “đừng làm user tự tin thái quá vào chi tiết chưa chắc.” Chi tiết nhiễu: Helix công bố một báo cáo bền vững 90 trang cùng ngày, đầy biểu đồ; ban quản trị nói “ai cần chi tiết thì đọc ESG.” Email chủ tịch ngày 20 tháng 1: “Data room chỉ mở cho long-only. Đừng để short-seller đọc duration gap.”",
  "model": "Đặc tính quyết định: Understandability không cho phép cắt thông tin cần thiết — CF.2.34–2.35. Concise là cách trình bày, không phải xóa hiện tượng. Data room làm obscuring (CF.2.11). Cost constraint do IASB cân khi viết chuẩn mực, listed group không tự miễn notes. Aggregation quá mức làm unlike items look alike. Timeliness, free from error của số mặt, verifiability, prudence “đừng tự tin thái quá” là nhiễu. Báo cáo ESG 90 trang không thay note IFRS. Email hạn chế short-seller là thao túng, không phải understandability.",
},
{
  "id": 24,
  "title": "Một nhà máy bị phá hủy sau ngày báo cáo",
  "company": "Ironclad Manufacturing",
  "difficulty": "Khó",
  "primary": "Thích hợp của sự kiện sau ngày khóa sổ không điều chỉnh",
  "primaryKey": "relevance",
  "cf": "CF.2.6–2.8",
  "distractors": ["Có thể so sánh như đặc tính nền tảng", "Không sai sót (Free from error)", "Trung lập (Neutrality)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["subsequent", "non-adjusting", "thuyết minh", "IAS 10", "predictive", "cháy", "thích hợp"],
  "scenario": "Ngày báo cáo của Ironclad Manufacturing là 31 tháng 12 năm 20X6 và báo cáo tài chính được phê duyệt ngày 28 tháng 2 năm 20X7. Ngày 5 tháng 1 năm 20X7 một vụ cháy đã phá hủy nhà máy duy nhất của công ty. Giá trị ghi sổ của nhà máy tại ngày 31 tháng 12 là 70 triệu CU, bằng 31% tổng tài sản. Phạm vi bảo hiểm đang bị tranh chấp và khả năng thu hồi không chắc chắn. Sản xuất đã dừng và công suất thay thế không thuê được trước quý 3 năm 20X7. Ban quản trị không điều chỉnh các số năm 20X6 cũng không thuyết minh vụ cháy. Tờ trình hội đồng nêu rằng vụ cháy xảy ra sau ngày báo cáo, đây là sự kiện năm 20X7, và ghi nhận hay thậm chí nhấn mạnh nó trong báo cáo năm 20X6 sẽ trộn các kỳ và phá hủy khả năng so sánh. Giám đốc tài chính gọi Có thể so sánh (Comparability) là đặc tính nền tảng bị đe dọa; rằng số 31/12 “không sai” nên Không sai sót (Free from error); rằng thuyết minh cháy sẽ “dọa user bán tháo” nên im lặng mới Trung lập (Neutrality); và rằng định giá tổn thất bảo hiểm tốn 0,7 triệu CU — Ràng buộc chi phí (Cost constraint). Chi tiết nhiễu: ngày 12 tháng 12 năm 20X6 một kho phụ bị dột, thiệt hại 0,2 triệu CU, đã ghi nhận đúng trong 20X6; ban quản trị nói “mọi tổn thất tài sản đều thuộc kỳ xảy ra — cháy tháng 1 cũng vậy, không note.” Email CEO ngày 8 tháng 1: “Đừng ghi note. Guidance 20X7 chưa sửa. Để Q1 hấp thụ.”",
  "model": "Đặc tính quyết định: Relevance (predictive value). Non-adjusting subsequent event (IAS 10): không sửa số 20X6 nhưng phải thuyết minh nếu material. Im lặng đến 28/2 là obscuring. Comparability không bị phá bởi một note; ngược lại note ngăn user suy ra sai rằng năng lực sản xuất còn nguyên. Free from error của số 31/12, “neutrality” kiểu đừng dọa user, cost constraint là nhiễu. Kho phụ dột 0,2 triệu CU là adjusting event trong kỳ — khác cháy sau khóa sổ.",
},
{
  "id": 25,
  "title": "Quá tốn kém để đếm 40% tài sản",
  "company": "Granite Materials",
  "difficulty": "Khó",
  "primary": "Ràng buộc chi phí bị từng đơn vị áp dụng sai",
  "primaryKey": "cost constraint",
  "cf": "CF.2.39–2.43",
  "distractors": ["Kịp thời (Timeliness)", "Dễ hiểu (Understandability)", "Thận trọng (Prudence)", "Có thể so sánh (Comparability)"],
  "keywords": ["cost constraint", "IASB", "không miễn trừ", "kiểm kê", "11%", "chi phí"],
  "scenario": "Granite Materials giữ các đống đá nghiền tại bốn mươi điểm. Hàng tồn kho đại diện 40% tổng tài sản. Năm 20X6 ban quản trị đã hủy kiểm kê cuối năm tại ba mươi mốt điểm và cuốn số lượng về trước từ lần đếm năm 20X4, chỉ điều chỉnh theo sản lượng và xuất kho đã ghi nhận. Tờ trình hội đồng viện dẫn ràng buộc chi phí của Khung khái niệm: đếm hết mọi đống sẽ tốn 1,2 triệu CU khảo sát; người sử dụng sẽ không trả thêm cho cổ phiếu của chúng ta chỉ vì chúng ta đếm đá. Một mẫu đếm hoàn tất tại chín điểm còn lại cho thấy số lượng thấp hơn sổ cuốn 11%. Không điều chỉnh nào được thực hiện cho các điểm chưa đếm và không mô tả hạn chế nào xuất hiện trong thuyết minh. Giám đốc tài chính thêm rằng đếm hết sẽ lùi phát hành sang tháng 4 (Timeliness); rằng thuyết minh phương pháp cuốn “làm user rối” (Understandability); rằng giữ sổ cuốn cao hơn là ngược với Prudence nên “chúng tôi đã thận trọng bằng cách không đếm”; và rằng hai mỏ ngang hàng cũng cuốn số hai năm một lần (Comparability). Chi tiết nhiễu: Granite đếm đúng 100% phụ tùng nhà xưởng trị giá 1,4 triệu CU (2% tài sản) và thuyết minh rất chi tiết; ban quản trị nói “chính sách kiểm kê của chúng tôi nghiêm.” Email COO ngày 1 tháng 12: “11% lệch ở mẫu. Đừng ngoại suy. Covenant tồn kho/tài sản sẽ vỡ.”",
  "model": "Đặc tính quyết định: Cost constraint bị áp dụng sai — CF.2.39–2.43. Board cân cost/benefit khi xây chuẩn mực, không phải từng entity tự loại yêu cầu. Mẫu đã sai 11% → số không còn faithful / free from error. Phải kiểm kê hoặc phương pháp thay thế đáng tin, và thuyết minh limitation. Timeliness, understandability, “prudence bằng cách không đếm,” comparability với peer cuốn số là nhiễu. Phụ tùng 2% đếm đúng không cứu 40% đá. Email covenant là động cơ.",
},
{
  "id": 26,
  "title": "Một giá bên liên quan đã cũ so với một DCF rất rộng",
  "company": "Quartz Biologics",
  "difficulty": "Rất khó",
  "primary": "Đánh đổi CF.2.22 giữa thích hợp và trình bày trung thực",
  "primaryKey": "trade-off",
  "cf": "CF.2.21–2.22",
  "distractors": ["Có thể so sánh (Comparability)", "Kịp thời (Timeliness)", "Thận trọng (Prudence)", "Chỉ trọng yếu (Materiality)"],
  "keywords": ["trade-off", "2.22", "range", "uncertainty", "relevant", "faithful", "đánh đổi"],
  "scenario": "Quartz Biologics nắm 12% một công ty liệu pháp gene chưa niêm yết. Tại ngày 31 tháng 12 năm 20X6 tồn tại hai ứng viên đo lường. Thứ nhất là giá trong giao dịch gần nhất, mười tám tháng trước, 22 triệu CU; giao dịch đó diễn ra giữa các nhà sáng lập liên quan và không có giao dịch ngang giá nào sau đó. Thứ hai là một định giá chiết khấu dòng tiền hiện tại do Quartz lập, cho ra khoảng 19 triệu CU đến 140 triệu CU tùy kịch bản phê duyệt của FDA; điểm ban quản trị ưa thích trong khoảng đó là 95 triệu CU. Giám đốc tài chính lập luận rằng Framework đòi hỏi thông tin thích hợp nhất và giá mười tám tháng đã cũ, nên 95 triệu CU phải được ghi sổ. Đối tác kiểm toán lập luận rằng 95 triệu CU không thể là một trình bày đủ trung thực và rằng Quartz nên giữ 22 triệu CU hoặc không đo lại. Ủy ban kiểm toán chia ba: một người muốn 19 triệu CU vì Prudence; một người muốn 22 triệu CU để Có thể so sánh (Comparability) với lần công bố trước; một người nói chênh 73 triệu CU “chỉ là FV, dưới 3% tổng tài sản” nên Trọng yếu (Materiality) không bắt buộc đổi. Chạy thêm kịch bản FDA được cho là sẽ lùi duyệt (Timeliness). Chi tiết nhiễu: Quartz còn một cổ phiếu niêm yết 4 triệu CU đo theo giá đóng cửa 31/12; CFO nói “cùng chính sách FV — luôn lấy số mới nhất, không phải số cũ.” Email CEO ngày 20 tháng 12: “Covenant equity 80 triệu CU. 22 triệu là chết. 95 triệu sống. Chọn 95.”",
  "model": "Đặc tính quyết định: trade-off Relevance vs Faithful representation — CF.2.21–2.22. Most relevant có lẽ là ước tính hiện tại, không phải giá 18 tháng bên liên quan. Nhưng CU95m trong range CU19–140m, chọn điểm vì management/covenant, uncertainty cực cao. Useful nhất thường là ước tính kèm mô tả uncertainty / công bố range, không phải một điểm im lặng cũng không neo mãi CU22m như current value. Prudence mút dưới, comparability với số cũ, materiality 3%, timeliness là nhiễu. Cổ phiếu niêm yết Level 1 không phải cùng hiện tượng.",
},
{
  "id": 27,
  "title": "EBITDA điều chỉnh trên mặt báo cáo, lãi IFRS trong thuyết minh",
  "company": "Pulse Fitness",
  "difficulty": "Khó",
  "primary": "Trung lập trong trình bày kết quả hoạt động",
  "primaryKey": "neutrality",
  "cf": "CF.2.15",
  "distractors": ["Kịp thời (Timeliness)", "Có thể kiểm chứng (Verifiability)", "Ràng buộc chi phí (Cost constraint)", "Thận trọng (Prudence)"],
  "keywords": ["EBITDA", "emphasise", "neutral", "IFRS 18", "de-emphas", "trung lập"],
  "scenario": "Pulse Fitness trình bày “Lợi nhuận hoạt động quản trị (EBITDA điều chỉnh)” in đậm như dòng cuối của báo cáo lãi lỗ. Lợi nhuận IFRS trong năm là 12 triệu CU. EBITDA điều chỉnh là 41 triệu CU sau khi cộng lại các khoản thanh toán trên cơ sở cổ phiếu, một chương trình tái cấu trúc, một khoản được mô tả là “thuê chuẩn hóa” (normalised rent) và “khấu hao phi tiền mặt.” Một đối chiếu xuất hiện ở Thuyết minh 28. Mọi biểu đồ ở nửa đầu báo cáo thường niên, và trang đầu thông cáo kết quả, chỉ dùng EBITDA điều chỉnh. Lý do của ban quản trị là người sử dụng thấy EBITDA thích hợp hơn lợi nhuận IFRS và relevance đứng trước. Không có trình bày lợi nhuận IFRS nổi bật tương đương trên mặt các báo cáo chính. Giám đốc tài chính gọi việc cộng khấu hao là Prudence “loại nhiễu phi tiền mặt”; rằng 41 triệu CU tái lập được từ note 28 nên Có thể kiểm chứng (Verifiability); rằng in hai chỉ tiêu nổi bật sẽ làm booklet dày thêm và lùi in ấn (Cost constraint, Timeliness). Chi tiết nhiễu: Pulse công bố đúng EPS IFRS trên mặt báo cáo, cỡ chữ nhỏ hơn một bậc so với adjusted EBITDA; ban quản trị nói “IFRS không bị giấu.” Email IR ngày 6 tháng 2: “Keep IFRS profit in the note. Buy-side models start from 41.”",
  "model": "Đặc tính quyết định: Neutrality trong lựa chọn và trình bày — CF.2.15. Không nhấn/làm mờ để hướng phản ứng của user. Đưa adjusted EBITDA thành dòng cuối đậm, chôn IFRS profit là de-emphasising. Relevance không đứng trên FR (CF.2.20). MPM hữu ích nếu minh bạch, không át via, reconcile rõ. Verifiability của note 28, prudence “phi tiền mặt,” cost/timeliness in ấn là nhiễu. EPS IFRS cỡ nhỏ không phải equally prominent.",
},
{
  "id": 28,
  "title": "Một dòng cho mọi nghĩa vụ có thể nhấn chìm công ty",
  "company": "HarborChem",
  "difficulty": "Khó",
  "primary": "Đầy đủ khi gộp các khoản dự phòng",
  "primaryKey": "completeness",
  "cf": "CF.2.14 / CF.2.11",
  "distractors": ["Kịp thời (Timeliness)", "Chỉ có thể so sánh (Comparability)", "Chỉ không sai sót (Free from error)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["aggregat", "complete", "obscur", "range", "investigation", "unlike", "đầy đủ"],
  "scenario": "HarborChem trình bày một dòng duy nhất “Dự phòng 88 triệu CU.” Sổ cái bên dưới gồm phục hồi môi trường 18 triệu CU, bảo hành 7 triệu CU, hợp đồng onerous 9 triệu CU, tái cấu trúc 5 triệu CU, và một cuộc điều tra luật cạnh tranh mà luật sư nói có thể tạo ra khoản phạt từ không đến 400 triệu CU, trong đó ban quản trị đã ghi 12 triệu CU ở mút dưới khoảng của chính họ. Thêm 37 triệu CU được xếp “khác,” trong đó 30 triệu CU là một bảo lãnh không dán nhãn khi bán một công ty con. Không có tách khoản, không có khoảng, không độ nhạy và không mô tả cuộc điều tra hay bảo lãnh trong thuyết minh. Ban quản trị cho rằng tổng số đã trọng yếu nên đủ. Giám đốc tài chính viết rằng 88 triệu CU cộng đúng các dòng sổ cái nên Không sai sót (Free from error); rằng hai hóa chất ngang hàng cũng một dòng provisions (Comparability); rằng viết năm trang tách khoản sẽ lùi nộp (Timeliness) và tốn phí luật sư cạnh tranh (Cost constraint). Chi tiết nhiễu: HarborChem thuyết minh rất chi tiết một khoản phải trả thương mại 22 triệu CU theo tuổi nợ; ban quản trị nói “nợ thì chúng tôi luôn tách.” Email luật sư ngày 3 tháng 1: “Fine could be 400. Booking 12 is the number that keeps going concern off the table.”",
  "model": "Đặc tính quyết định: Completeness kết hợp materiality-as-obscuring. Điều tra CU0–400m ghi CU12m rồi trộn với bảo hành là unlike things look alike. Predictive value mất. Phải tách các hiện tượng khác bản chất và công bố range của investigation + indemnity. Ghi nhận tổng không thay completeness của mô tả. Free from error của phép cộng, comparability với peer một dòng, timeliness/cost là nhiễu. Tuổi nợ phải trả thương mại không bù cho việc gộp điều tra 0–400.",
},
{
  "id": 29,
  "title": "Doanh thu bill-and-hold mà hàng không bao giờ rời kho",
  "company": "Vertex Equipment",
  "difficulty": "Khó",
  "primary": "Trình bày trung thực — chưa chuyển giao kiểm soát",
  "primaryKey": "faithful representation",
  "cf": "CF.2.12 / CF.2.20",
  "distractors": ["Kịp thời (Timeliness)", "Có thể so sánh (Comparability)", "Dễ hiểu (Understandability)", "Ràng buộc chi phí (Cost constraint)"],
  "keywords": ["control", "bill-and-hold", "không doanh thu", "substance", "return", "kiểm soát", "trung thực"],
  "scenario": "Ngày 29 tháng 12 năm 20X6 Vertex Equipment đã ghi nhận 35 triệu CU doanh thu theo một thỏa thuận bill-and-hold với một nhà phân phối. Hàng vẫn nằm trong kho của Vertex. Nhà phân phối có quyền đơn phương trả bất kỳ món nào chưa bán đến ngày 30 tháng 6 năm 20X7, chưa thanh toán, và chưa ký một thỏa thuận lưu kho riêng. Vertex vẫn bảo hiểm hàng và kiểm soát lối vào khoang chứa. Nếu không có giao dịch này Vertex sẽ trượt guidance lợi nhuận đã công bố 6%. Lập trường của ban quản trị là một hóa đơn pháp lý đã được phát hành nên việc bán tồn tại; người sử dụng muốn thấy sổ đặt hàng biến thành doanh thu năm nay; thông tin đó có giá trị xác nhận (confirmatory value) đối với guidance của chúng ta. Giám đốc tài chính thêm rằng hai nhà sản xuất máy ngang hàng cũng ghi bill-and-hold cuối năm (Comparability); rằng tách “đơn hàng chưa giao” ra thuyết minh sẽ làm user rối (Understandability); rằng chờ hàng xuất kho thật sẽ lùi ghi nhận sang tháng 1 và “làm mất tính kịp thời của confirmatory value” (Timeliness); và rằng dựng hợp đồng lưu kho riêng tốn phí pháp lý (Cost constraint). Chi tiết nhiễu: Vertex có một lô 2 triệu CU đã giao, đã thu tiền, kiểm soát đã chuyển ngày 27 tháng 12 — ghi nhận đúng; ban quản trị gọi đó là “cùng chính sách cut-off.” Email nhà phân phối ngày 28 tháng 12: “Invoice us if you need the number. We have no space and no obligation to take the goods.”",
  "model": "Đặc tính quyết định: Faithful representation of control/substance, không phải legal invoice. Hàng chưa chuyển giao kiểm soát: còn kho người bán, quyền trả hàng, chưa trả tiền. Hiện tượng là inventory + executory arrangement. Confirmatory value nhân tạo không cứu mô tả không faithful. Thông tin backlog ở thuyết minh, không trên dòng revenue. Comparability với peer bill-and-hold, understandability, timeliness của guidance, cost của hợp đồng kho là nhiễu. Lô 2 triệu CU giao thật ngày 27/12 khác bản chất.",
},
{
  "id": 30,
  "title": "Bốn khoản mục và một danh sách mọi đặc tính",
  "company": "MultiSignal Holdings",
  "difficulty": "Rất khó",
  "primary": "Thứ tự ưu tiên: nền tảng rồi nâng cao, rồi chi phí",
  "primaryKey": "hierarchy",
  "cf": "CF.2.21 / CF.2.37",
  "distractors": ["Luôn là trọng yếu", "Luôn là thận trọng", "Luôn là có thể so sánh", "Ràng buộc chi phí luôn thắng"],
  "keywords": ["hierarchy", "quyết định", "fundamental", "enhancing", "(i)", "(iv)", "neutrality", "thứ tự"],
  "scenario": "MultiSignal Holdings đang khóa sổ báo cáo năm 20X6. Bốn khoản chưa xử lý đến cùng một buổi chiều. Thứ nhất, một lỗi triển khai phần mềm đã đếm trùng tiền mặt 4 triệu CU trong hai tuần tháng 12; lỗi được phát hiện khi kiểm toán và đã được đảo trước khi phê duyệt phát hành. Thứ hai, hội đồng đã hứa công khai với người sử dụng một phân tích độ nhạy liên quan khí hậu trong báo cáo năm 20X6; mô hình chưa xong và ban quản trị muốn phát hành đúng hạn tháng 2 mà không có phân tích đó. Thứ ba, một đối thủ niêm yết lớn hơn cắt doanh thu theo một mốc lạ; giám đốc thương mại muốn MultiSignal theo cùng mốc để nhà đầu tư so sánh chúng ta, dù hợp đồng của MultiSignal chuyển giao kiểm soát ở một thời điểm khác. Thứ tư, một tài sản sinh học Cấp 3 chỉ đứng được như một khoảng rộng; ban quản trị muốn ghi mút trên của khoảng để còn trong một covenant đòn bẩy. Tổ kỹ thuật đã viết mọi đặc tính định tính cạnh mọi khoản và không thống nhất đặc tính nào thật sự quyết định từng vấn đề. Tờ trình đề xuất một “quy tắc bỏ túi”: luôn chọn Trọng yếu nếu số trên 1% tài sản; luôn chọn Prudence nếu có covenant; luôn chọn Comparability nếu có peer; và nếu hết thời gian thì Ràng buộc chi phí thắng. Chi tiết nhiễu: cùng buổi chiều còn một khoản thứ năm — hóa đơn văn phòng phẩm 12.000 CU bị ghi nhầm kỳ, đã sửa trong 10 phút — được tổ kỹ thuật gắn đủ bảy đặc tính “cho nhất quán quy trình.” Email CFO: “Pick comparability for revenue, prudence for bio assets, cost for climate. Ship on 28 February.”",
  "model": "Đặc tính quyết định của cả case: xếp tầng QC. (i) Free from error — đã sửa trước ban hành, depiction cuối faithful. (ii) Relevance + completeness của thông tin đã hứa, không phải timeliness. (iii) Faithful representation thắng comparability with rival (CF.2.37). (iv) Neutrality (chọn mút trên vì covenant) là quyết định, không chỉ measurement uncertainty. Đừng liệt kê hết QC; chỉ ra QC quyết định từng mục. Quy tắc bỏ túi “luôn materiality / luôn prudence / luôn comparability / cost luôn thắng” là sai hierarchy. Hóa đơn 12.000 CU là nhiễu.",
},
]
