/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankRouteImport } from './routes/bank'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as EssayIdRouteImport } from './routes/essay.$id'
import { Route as McqIdRouteImport } from './routes/mcq.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayIdRoute = EssayIdRouteImport.update({
  id: '/essay/$id',
  path: '/essay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const McqIdRoute = McqIdRouteImport.update({
  id: '/mcq/$id',
  path: '/mcq/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/exam': typeof ExamRoute
  '/essay/$id': typeof EssayIdRoute
  '/mcq/$id': typeof McqIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/exam': typeof ExamRoute
  '/essay/$id': typeof EssayIdRoute
  '/mcq/$id': typeof McqIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/exam': typeof ExamRoute
  '/essay/$id': typeof EssayIdRoute
  '/mcq/$id': typeof McqIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bank' | '/exam' | '/essay/$id' | '/mcq/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bank' | '/exam' | '/essay/$id' | '/mcq/$id'
  id: '__root__' | '/' | '/bank' | '/exam' | '/essay/$id' | '/mcq/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  ExamRoute: typeof ExamRoute
  EssayIdRoute: typeof EssayIdRoute
  McqIdRoute: typeof McqIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay/$id': {
      id: '/essay/$id'
      path: '/essay/$id'
      fullPath: '/essay/$id'
      preLoaderRoute: typeof EssayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcq/$id': {
      id: '/mcq/$id'
      path: '/mcq/$id'
      fullPath: '/mcq/$id'
      preLoaderRoute: typeof McqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  ExamRoute: ExamRoute,
  EssayIdRoute: EssayIdRoute,
  McqIdRoute: McqIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
